### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by YaroslavShutov** [AndroidIDEOfficial/AndroidIDE#1010]
### What happened?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: 2201117TG
ABI: arm64-v8a
SDK version: 31
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalArgumentException: COLOR resource 're' not found
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.resolveResourceReference(basicParseUtils.kt:5)
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.parseReference(basicParseUtils.kt:381)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(AbstractParser.kt:10)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(AbstractParser.kt:15)
	at com.itsaky.androidide.inflater.internal.adapters.ViewAdapter$createAttrHandlers$2.invoke(ViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(IViewAdapter.kt:20)
	at com.itsaky.androidide.inflater.IViewAdapter$apply$1.invoke(IViewAdapter.kt:10)
	at com.itsaky.androidide.inflater.IViewAdapter.doApply(IViewAdapter.kt:62)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(IViewAdapter.kt:16)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(ViewImpl.kt:40)
	at com.itsaky.androidide.uidesigner.fragments.AttrValueEditorFragment$showAttrInfo$1$2.invoke(AttrValueEditorFragment.kt:65)
	at com.itsaky.androidide.uidesigner.utils.ValueCompletionProvider$afterTextChanged$1$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:17)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: 2201117TG
ABI: arm64-v8a
SDK version: 31
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalArgumentException: COLOR resource 're' not found
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.resolveResourceReference(basicParseUtils.kt:5)
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.parseReference(basicParseUtils.kt:381)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(AbstractParser.kt:10)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(AbstractParser.kt:15)
	at com.itsaky.androidide.inflater.internal.adapters.ViewAdapter$createAttrHandlers$2.invoke(ViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(IViewAdapter.kt:20)
	at com.itsaky.androidide.inflater.IViewAdapter$apply$1.invoke(IViewAdapter.kt:10)
	at com.itsaky.androidide.inflater.IViewAdapter.doApply(IViewAdapter.kt:62)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(IViewAdapter.kt:16)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(ViewImpl.kt:40)
	at com.itsaky.androidide.uidesigner.fragments.AttrValueEditorFragment$showAttrInfo$1$2.invoke(AttrValueEditorFragment.kt:65)
	at com.itsaky.androidide.uidesigner.utils.ValueCompletionProvider$afterTextChanged$1$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:17)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This was fixed in 111a15d. However, the commit is not part of any release yet. The fix will be available in next release.
