### ISSUE TITLE
[Bug]: ArrayIndexOutOfBoundsException in IDEEditor

### ISSUE THREAD

**Issue by asm-01** [AndroidIDEOfficial/AndroidIDE#1038]
### What happened?

I'm using pre-released version from github action [this commit](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/5178919221)

I don't know why but the editor was always freezing while editing even though it's not very large file (only have 100+ lines in this case). It's keep delaying whenever I tried to edit.

### What's the expected behavior?

NA

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: 220233L2G
ABI: armeabi-v7a
SDK version: 30
App version: v2.4.1-beta.internal.1+branch.dev.commit.e6c7d1a.timestamp.20230605152336 (241)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: index = 0, length = 0
	at io.github.rosemoe.sora.util.BlockIntList.set(BlockIntList.java:201)
	at io.github.rosemoe.sora.widget.layout.LineBreakLayout.afterInsert(LineBreakLayout.java:149)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(CodeEditor.java:4540)
	at io.github.rosemoe.sora.text.Content.dispatchAfterInsert(Content.java:1022)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:411)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:350)
	at com.itsaky.androidide.editor.ui.IDEEditor.append(IDEEditor.java:460)
	at com.itsaky.androidide.fragments.LogViewFragment.append$lambda$2$lambda$1(LogViewFragment.kt:153)
	at com.itsaky.androidide.fragments.LogViewFragment.$r8$lambda$synKpd97Jet_i4IY_eYr-pE7K7A(Unknown Source:0)
	at com.itsaky.androidide.fragments.LogViewFragment$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.fragments.LogViewFragment.append(LogViewFragment.kt:153)
	at com.itsaky.androidide.fragments.LogViewFragment.access$append(LogViewFragment.kt:45)
	at com.itsaky.androidide.fragments.LogViewFragment$logRunnable$1.run(LogViewFragment.kt:93)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8097)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you test the latest build? The recent builds use tree-sitter for highlighting logs, the commit you're using uses the previous implementation (`LogLineTokenizer`).

If you face the crash even with the latest build, please reopen this issue.
