### ISSUE TITLE
[Bug]: AndroidIDE crashed

### ISSUE THREAD

**Issue by sourav-kum** [AndroidIDEOfficial/AndroidIDE#1050]
### What happened?

AndroidIDE crashed in middle of editing

### What's the expected behavior?

It should not crash in middle of editing of files.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A346E
ABI: arm64-v8a
SDK version: 33
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke interface method 'openjdk.source.tree.BlockTree openjdk.source.tree.MethodTree.getBody()' on a null object reference
	at com.itsaky.androidide.lsp.java.rewrite.AddException$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:44)
	at com.itsaky.androidide.lsp.java.compiler.SynchronizedTask.get(SynchronizedTask.java:8)
	at com.itsaky.androidide.lsp.java.rewrite.AddException.rewrite(AddException.java:32)
	at com.itsaky.androidide.lsp.java.rewrite.Rewrite.asCodeActions(Rewrite.java:1)
	at com.itsaky.androidide.lsp.java.actions.BaseJavaCodeAction.performCodeAction(BaseJavaCodeAction.kt:55)
	at com.itsaky.androidide.lsp.java.actions.diagnostics.AddThrowsAction.postExec(AddThrowsAction.kt:26)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$execInBackground$2$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:30)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you provide a way to reproduce this issue? I can't think of a scenario in which the `AddThrows` action is shown for a method which doesn't have a method body.

**Comment by sourav-kum** [comment]
Sorry, I don't know how to reproduce that issue. I was editing a file and suddenly crashed. Sorry, I cannot help much.Sent from my Galaxy
-------- Original message --------From: Akash Yadav ***@***.***> Date: 24/06/23  11:18 pm  (GMT+05:30) To: AndroidIDEOfficial/AndroidIDE ***@***.***> Cc: sourav-kum ***@***.***>, Author ***@***.***> Subject: Re: [AndroidIDEOfficial/AndroidIDE] [Bug]: AndroidIDE crashed (Issue #1050) 
Can you provide a way to reproduce this issue? I can't think of a scenario in which the AddThrows action is shown for a method which doesn't have a method body.
