### ISSUE TITLE
bbb

### ISSUE THREAD

**Issue by SuccessfulPerson2023** [AndroidIDEOfficial/AndroidIDE#1083]
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G970U
ABI: arm64-v8a
SDK version: 31
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2235)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2268)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by itsaky** [comment]
Duplicate of #870.
