### ISSUE TITLE
[Bug]: crash when opening library project

### ISSUE THREAD

**Issue by andihasan97** [AndroidIDEOfficial/AndroidIDE#1102]
### What happened?

crashes when opening library project files, even though prior to version 2.5.0 it can be opened and can run unit tests

### What's the expected behavior?

fix it as before it can be opened and can run tasks for the library 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: vivo
Device: vivo1901
ABI: arm64-v8a
SDK version: 30
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.itsaky.androidide.models.OpenedFile
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity$onStart$2.invoke(Unknown Source:52)
	at com.itsaky.androidide.templates.impl.BaseKt$baseProjectImpl$1.invoke(SourceFile:18)
	at com.itsaky.androidide.tasks.TaskExecutorKt$$ExternalSyntheticLambda1.complete(Unknown Source:162)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:857)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I was planning to release v2.5.0-beta yesterday, but I had to postpone it due to this specific issue.

I'll work on it and publish the release ASAP. Till then, you're not advised to use that build.

**Comment by andihasan97** [comment]
> 

okay, I understand 👍

**Comment by JWJIW** [comment]
ok no problem friend you can work quietly Enviado do meu Galaxy
-------- Mensagem original --------De : Akash Yadav ***@***.***> Data: 14/07/2023  3:10 AM  (GMT-03:00) Para: AndroidIDEOfficial/AndroidIDE ***@***.***> Cc: Subscribed ***@***.***> Assunto: Re: [AndroidIDEOfficial/AndroidIDE] [Bug]: crash when opening library project (Issue #1102) 
I was planning to release v2.5.0-beta yesterday, but I had to postpone it due to this specific issue.
I'll work on it and publish the release ASAP. Till then, you're not advised to use that build.
