### ISSUE TITLE
[Bug]: IDE Crash when opening project

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1108]
### What happened?

When I closed &  re-opened the project ide crashed 

### What's the expected behavior?

.

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-J415F
ABI: armeabi-v7a
SDK version: 28
App version: v2.5.0-beta.internal.1+branch.dev.commit.bdf1f9e.timestamp.20230715063520 (250)

 Stacktrace: 
java.lang.IllegalArgumentException: Syntax highlights query is invalid
	at io.github.rosemoe.sora.editor.ts.TsLanguageSpec.<init>(TsLanguageSpec.kt:125)
	at com.itsaky.androidide.editor.schemes.LanguageSpecProvider.getLanguageSpec(LanguageSpecProvider.kt:51)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:58)
	at com.itsaky.androidide.editor.language.log.LogLanguage.<init>(LogLanguage.kt:31)
	at com.itsaky.androidide.fragments.LogViewFragment$onViewCreated$2.invoke(LogViewFragment.kt:244)
	at com.itsaky.androidide.fragments.LogViewFragment$onViewCreated$2.invoke(LogViewFragment.kt:243)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readScheme$3.invoke(IDEColorSchemeProvider.kt:143)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readScheme$3.invoke(IDEColorSchemeProvider.kt:135)
	at com.itsaky.androidide.tasks.TaskExecutorKt$sam$com_itsaky_androidide_tasks_TaskExecutor_CallbackWithError$0.complete(Unknown Source:2)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2.invoke$lambda$0(TaskExecutor.kt:63)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2.$r8$lambda$IhA-YFhAfBBwhoc4NxFxsoc9sco(Unknown Source:0)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7094)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Use the latest build.
