### ISSUE TITLE
[Bug]: 反复的点击创建项目和离开发生了崩溃

### ISSUE THREAD

**Issue by CrescentEcho** [AndroidIDEOfficial/AndroidIDE#1109]
### What happened?

反复的点击创建项目和离开时发生崩溃

### What's the expected behavior?

反复的点击创建项目和离开时发生了崩溃

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: vivo
Device: V1901A
ABI: arm64-v8a
SDK version: 28
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IllegalStateException: Invalid screen states. Previous: 1 Current: 1
	at com.itsaky.androidide.activities.MainActivity.onScreenChanged(Unknown Source:163)
	at androidx.work.JobListenableFuture$1.invoke(SourceFile:87)
	at com.itsaky.androidide.activities.MainActivity$$ExternalSyntheticLambda0.onChanged(Unknown Source:114)
	at androidx.lifecycle.MutableLiveData.considerNotify(Unknown Source:29)
	at androidx.lifecycle.MutableLiveData.dispatchingValue(Unknown Source:55)
	at androidx.lifecycle.MutableLiveData.setValue(Unknown Source:14)
	at com.itsaky.androidide.viewmodel.MainViewModel.setScreen(Unknown Source:28)
	at com.itsaky.androidide.fragments.TemplateDetailsFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:20)
	at android.view.View.performClick(View.java:6648)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:6621)
	at android.view.View.access$3100(View.java:792)
	at android.view.View$PerformClick.run(View.java:26334)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This should have been fixed in 3c8c4f7222314260ff17bfefafb14bda0d5dc790. Reopen this issue if it isn't.
