### ISSUE TITLE
[Bug]: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by FaultyxDx** [AndroidIDEOfficial/AndroidIDE#1110]
### What happened?

AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2095
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:20)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4837)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@2252a87: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4857)
	at android.app.ActivityThread.access$2200(ActivityThread.java:254)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2227)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

### What's the expected behavior?

idk 

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2095
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:20)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4837)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@2252a87: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4857)
	at android.app.ActivityThread.access$2200(ActivityThread.java:254)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2227)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Should have been fixed in 440358a814139878bdedf3ae12de96b61e1200a2. Reopen this issue if it isn't.
