### ISSUE TITLE
[Bug]: While reopening file after closing

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1113]
### What happened?

When I reloaded color scheme when it was highlighting code properly but showing error but after reloading showing white text I tried again then also white text I  closed file then it was showing white text in another file I closed both MainActivity and AndroidManifiest and try reopening file then ide crashed 

### What's the expected behavior?

.

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-J415F
ABI: armeabi-v7a
SDK version: 28
App version: v2.5.0-beta.internal.1+branch.dev.commit.bdf1f9e.timestamp.20230715063520 (250)

 Stacktrace: 
java.lang.IllegalArgumentException: query(name:code-blocks) parsing failed: Language at text offset 0
	at io.github.rosemoe.sora.editor.ts.UtilsKt.validateOrThrow(Utils.kt:39)
	at io.github.rosemoe.sora.editor.ts.TsLanguageSpec.<init>(TsLanguageSpec.kt:117)
	at com.itsaky.androidide.editor.schemes.LanguageSpecProvider.getLanguageSpec(LanguageSpecProvider.kt:51)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:58)
	at com.itsaky.androidide.editor.language.java.JavaLanguage.<init>(JavaLanguage.kt:39)
	at com.itsaky.androidide.editor.language.java.JavaLanguage.FACTORY$lambda$0(JavaLanguage.kt:46)
	at com.itsaky.androidide.editor.language.java.JavaLanguage.$r8$lambda$6CiJiGB0EHso74PE29UWS4GFdcs(Unknown Source:0)
	at com.itsaky.androidide.editor.language.java.JavaLanguage$$ExternalSyntheticLambda0.create(Unknown Source:0)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguageProvider.forFile(TreeSitterLanguageProvider.kt:34)
	at com.itsaky.androidide.editor.ui.IDEEditor.createLanguage(IDEEditor.java:1002)
	at com.itsaky.androidide.editor.ui.IDEEditor.setupLanguage(IDEEditor.java:958)
	at com.itsaky.androidide.ui.editor.CodeEditorView.postRead(CodeEditorView.java:163)
	at com.itsaky.androidide.ui.editor.CodeEditorView.lambda$new$0$com-itsaky-androidide-ui-editor-CodeEditorView(CodeEditorView.java:131)
	at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7094)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This issue has been fixed in the latest build.
