### ISSUE TITLE
[Bug]: something error on start

### ISSUE THREAD

**Issue by SoytanM** [AndroidIDEOfficial/AndroidIDE#1121]
### What happened?

App crashing

### What's the expected behavior?

.

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote7Pro
ABI: arm64-v8a
SDK version: 29
App version: v2.5.0-beta (250)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:856)
	at android.content.res.AssetManager.open(AssetManager.java:833)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1666)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This seems to be working fine in `v2.5.1-beta`. Make sure that you download the APK for your specific CPU ABI.

**Comment by itsaky** [comment]
I can confirm that this issue happens only if you install the `armeabi-v7a` variant on a `arm64-v8a` device.

Again, make sure that you download the APK for your specific CPU ABI.

**Comment by SoytanM** [comment]
I am using many apps made for armeabi-v7a cpu but my phone has arm64 cpu and it's don't have any problem..
So why it's crashing..

**Comment by SoytanM** [comment]
I realized that when I use arm64 app on my mobile my mobile heats up and the battery drains fast.. that why I want to use armeabi-v7a apps

**Comment by itsaky** [comment]
> I am using many apps made for armeabi-v7a cpu but my phone has arm64 cpu and it's don't have any problem..
So why is AndroidIDE crashing..

AndroidIDE includes architecture specific assets in the APK which helps to reduce the size of APK. When you open the terminal for the first time, it tries to install these assets. However, assets for your CPU arch are not included in the APK you installed, that's why the crash.
