### ISSUE TITLE
[bug] Android IDE crashed out of nowhere

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1132]
### What happened?

I saw that this error has apparently already been fixed, but it occurred to me 3 times in the 2.5.1-beta version If this serves as context: 2 times when closing the project and 1 time when opening the app, The start of the stacktrace is different than what was reported by someone else, but the cause seems to be the same.

### What's the expected behavior?

Dont crash

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: LGE
Device: LM-X420
ABI: armeabi-v7a
SDK version: 28
App version: v2.5.1-beta (251)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:23)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3862)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@40ccdd6: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3882)
	at android.app.ActivityThread.access$1700(ActivityThread.java:208)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1733)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Check if this is fixed in the latest build.

**Comment by Rafael2616** [comment]
I opened it and did several things and closed it several times and it didn't crash anymore

**Comment by itsaky** [comment]
Feel free to reopen this issue if you encounter this specific crash again.

**Comment by Rafael2616** [comment]
It seems that this bug is still happening, kasc with a lesser frequency, it doesn't prevent the use of the app, it only shows an error message when closing the project or when exiting the app (sometimes)

**Comment by itsaky** [comment]
> It seems that this bug is still happening, kasc with a lesser frequency, it doesn't prevent the use of the app, it only shows an error message when closing the project or when exiting the app (sometimes)

What error message?

**Comment by Rafael2616** [comment]
Exactly the same, sometimes with some variation, but always 'MultiLogSenderHandler.close()'
