### ISSUE TITLE
[Problema]: Problemas com fechamento do app

### ISSUE THREAD

**Issue by LKZINXSZ1VX** [AndroidIDEOfficial/AndroidIDE#1145]
### What happened?

Estou digitando o meu código, depois de um tempo ele fecha o app e mostra um erro de pthread_create.

### What's the expected behavior?

O comportamento esperado é que ele não feche durante a minha digitação do código.

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2006C3LII
ABI: armeabi-v7a
SDK version: 29
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:883)
	at com.itsaky.androidide.editor.ui.EditorCompletionWindow.requireCompletion(Unknown Source:144)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(Unknown Source:306)
	at io.github.rosemoe.sora.text.Content.insertInternal(Unknown Source:317)
	at io.github.rosemoe.sora.text.Content.insert(Unknown Source:9)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(Unknown Source:211)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(Unknown Source:327)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(Unknown Source:94)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:339)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Try reducing the `-Xmx` value in the `gradle.properties` file in your project's root folder.

**Comment by JWJIW** [comment]
Isso acontece com eu também , mais de maneira  deferente o quanto  eu coloco o app em segundo plano  ele fecha  e isso não deveria acontecer  eu tenho  um ótimo prosesador  e uma nível alto de memória rar

**Comment by itsaky** [comment]
> Isso acontece com eu também , mais de maneira deferente o quanto eu coloco o app em segundo plano ele fecha e isso não deveria acontecer eu tenho um ótimo prosesador e uma nível alto de memória rar

Use a translator. I don't understand any of this.

**Comment by JWJIW** [comment]
This happens to me too, more differently how much I put the app in the background it dates and this shouldn't happen I have a great processor and a high level of rar memory

**Comment by itsaky** [comment]
Closing in favor of #1694
