### ISSUE TITLE
[Bug]: unable to start building app

### ISSUE THREAD

**Issue by Pnu-kun** [AndroidIDEOfficial/AndroidIDE#1153]
### What happened?

I was trying to start a project and then this popped out

### What's the expected behavior?

I don't know what to write here

### What version of AndroidIDE you're using?

v2.5.0

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: realme
Device: RMX3231
ABI: armeabi-v7a
SDK version: 30
App version: v2.5.0-beta (250)

 Stacktrace: 
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:418)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:421)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Are you trying to install AndroidIDE in SD Card?
