### ISSUE TITLE
[bug]: NPE when I click in preview layout without layout files opened

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1176]
### What happened?

I don't use the layout feature, but I've noticed that if I have a layout and close it and try to preview it, the app hangs at an NPE

Video showing the issue:

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/0f141a06-62dc-4c7a-8afd-73a1d06a215a

### What's the expected behavior?

No crash

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: LGE
Device: LM-X420
ABI: armeabi-v7a
SDK version: 28
App version: v2.5.1-beta.internal.1+branch.dev.commit.86fbed8.timestamp.20230803142331 (251)

 Stacktrace: 
java.lang.NullPointerException
	at com.itsaky.androidide.actions.etc.PreviewLayoutAction.execAction(PreviewLayoutAction.kt:93)
	at com.itsaky.androidide.actions.etc.PreviewLayoutAction.execAction(PreviewLayoutAction.kt:37)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction$lambda$4(DefaultActionsRegistry.kt:180)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$dXsASD5DI7x0X3S7AhqTqILaCV8(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction(DefaultActionsRegistry.kt:179)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda$3(DefaultActionsRegistry.kt:169)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$PPRxnA5HN5W60216J1ZeVbR5hrk(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda3.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
	at android.view.View.performClick(View.java:6615)
	at android.view.View.performClickInternal(View.java:6587)
	at android.view.View.access$3500(View.java:784)
	at android.view.View$PerformClick.run(View.java:26050)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Most probably, the options menu is not being invalidated when a file is closed. I'll look into it.

**Comment by Rafael2616** [comment]
This can already be marked as done by commit #1251?

**Comment by itsaky** [comment]
There is another thing to improve regarding this issue. The options menu is not invalidated if the file is unsaved and you try to close the file.

**Comment by Rafael2616** [comment]
Ok
