### ISSUE TITLE
[Bug]: App crash when I add src:@drawable/ic_clear_grey in preview layout 

### ISSUE THREAD

**Issue by TanTai97o** [AndroidIDEOfficial/AndroidIDE#1189]
### What happened?

AndroidIDE crash report
Manufacturer: samsung
Device: SM
ABI: arm64-v8a
SDK version: 31
App version: v2.5.2-beta (252)

 Stacktrace: 
java.lang.IllegalStateException: You must call startParse(AndroidModule) first
	at com.google.common.base.Strings.getModule(Unknown Source:9)
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.parseReference(Unknown Source:116)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(SourceFile:5)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(Unknown Source:14)
	at com.itsaky.androidide.inflater.internal.adapters.ImageViewAdapter$createAttrHandlers$1.invoke(SourceFile:14)
	at com.itsaky.androidide.inflater.internal.adapters.ImageViewAdapter$createAttrHandlers$1.invoke(SourceFile:1)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(Unknown Source:23)
	at androidx.work.JobListenableFuture$1.invoke(SourceFile:75)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(Unknown Source:77)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(Unknown Source:39)
	at com.itsaky.androidide.inflater.internal.ViewImpl.addAttribute(Unknown Source:39)
	at com.itsaky.androidide.uidesigner.viewmodel.WorkspaceViewModel.notifyAttrUpdated(Unknown Source:48)
	at com.itsaky.androidide.uidesigner.fragments.ViewInfoSheet.onDismiss(Unknown Source:27)
	at androidx.fragment.app.DialogFragment$3.onDismiss(Unknown Source:6)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1825)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### What's the expected behavior?

Please release this fix as soon as possible

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in a29df43.
