### ISSUE TITLE
[Bug]: OutOfMemoryError

### ISSUE THREAD

**Issue by DevKumar00001** [AndroidIDEOfficial/AndroidIDE#1194]
### What happened?

Crash app while running

### What's the expected behavior?

AndroidIDE crash report

### What version of AndroidIDE you're using?

v2.5.2

### Relevant log output

```shell
Manufacturer: Xiaomi
Device: M2006C3MII
ABI: armeabi-v7a
SDK version: 29
App version: v2.5.2-beta (252)

 Stacktrace: 
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:883)
	at com.itsaky.androidide.editor.ui.EditorCompletionWindow.requireCompletion(Unknown Source:144)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(Unknown Source:306)
	at io.github.rosemoe.sora.text.Content.insertInternal(Unknown Source:317)
	at io.github.rosemoe.sora.text.Content.insert(Unknown Source:9)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(Unknown Source:211)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(Unknown Source:327)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(Unknown Source:94)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:339)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This is an `OutOfMemoryError`, you can try to reduce the `Xmx` value in your `gradle.properties` for now. I'll work on reducing the memory usage later.

**Comment by Alex3474247** [comment]
This issue is still actual. I have just got this error when were in sleep mode and more than 10-15 cpp files in editor were opened. Tried to switch back to IDE and this error occured.
AndroidIDE crash report
Manufacturer: HUAWEI
Device: MNA-LX9
ABI: arm64-v8a
SDK version: 31
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 5029528 free bytes and 4911KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:49)
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:45)
	at java.nio.CharBuffer.allocate(CharBuffer.java:172)
	at androidx.work.Operation$1.fromReader(Unknown Source:7)
	at com.itsaky.androidide.editor.language.incremental.BaseIncrementalAnalyzeManager.createStream(Unknown Source:8)
	at com.itsaky.androidide.editor.language.incremental.BaseIncrementalAnalyzeManager.tokenizeLine(Unknown Source:210)
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.initialize(Unknown Source:65)
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.handleMessage(Unknown Source:547)
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.run(Unknown Source:18)

**Comment by itsaky** [comment]
Closing in favor of #1694
