### ISSUE TITLE
[Bug]: Flash back

### ISSUE THREAD

**Issue by atsltooaki** [AndroidIDEOfficial/AndroidIDE#1195]
### What happened?

After the build is successful, close the project and a flashback occurs

### What's the expected behavior?

![Screenshot_2023-08-08-19-59-18-668_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/131748628/bdbe5486-bd5e-4212-8aad-662c5278c1c0)

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: 23013RK75C
ABI: arm64-v8a
SDK version: 33
App version: v2.5.2-beta.internal.1+branch.dev.commit.3abc07c.timestamp.20230807182521 (252)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1455)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.removeAllClients(MultiLogSenderHandler.kt:103)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(MultiLogSenderHandler.kt:115)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(LogReceiverImpl.kt:117)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(LogReceiverService.kt:67)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4876)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@43aeebd: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4896)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you check if the issue occurs in [this build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/5822734992)?

**Comment by atsltooaki** [comment]
This problem seems to be taking up memory or CPU is too high, and then killed by the system
