### ISSUE TITLE
[Bug]: Application crashed when clicking on undo.

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#1198]
### What happened?

The application crashed while I was undoing my code.

### What's the expected behavior?

Shouldn't crash.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2495
ABI: arm64-v8a
SDK version: 33
App version: v2.5.2-beta.internal.1+branch.dev.commit.3abc07c.timestamp.20230807182521 (252)

 Stacktrace: 
java.lang.IllegalStateException: Cannot access native object
	at com.itsaky.androidide.treesitter.TSNativeObject.checkAccess(TSNativeObject.java:51)
	at com.itsaky.androidide.treesitter.TSTree.getRootNode(TSTree.java:37)
	at io.github.rosemoe.sora.editor.ts.TsBracketPairs.getPairedBracketAt(TsBracketPairs.kt:51)
	at io.github.rosemoe.sora.widget.EditorStyleDelegate.lambda$postUpdateBracketPair$1$io-github-rosemoe-sora-widget-EditorStyleDelegate(EditorStyleDelegate.java:68)
	at io.github.rosemoe.sora.widget.EditorStyleDelegate$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at io.github.rosemoe.sora.widget.EditorStyleDelegate.runOnUiThread(EditorStyleDelegate.java:90)
	at io.github.rosemoe.sora.widget.EditorStyleDelegate.postUpdateBracketPair(EditorStyleDelegate.java:64)
	at io.github.rosemoe.sora.widget.EditorStyleDelegate.lambda$new$0$io-github-rosemoe-sora-widget-EditorStyleDelegate(EditorStyleDelegate.java:52)
	at io.github.rosemoe.sora.widget.EditorStyleDelegate$$ExternalSyntheticLambda2.onReceive(Unknown Source:4)
	at io.github.rosemoe.sora.event.EventManager.dispatchEvent(EventManager.java:226)
	at io.github.rosemoe.sora.widget.CodeEditor.dispatchEvent(CodeEditor.java:3711)
	at io.github.rosemoe.sora.widget.CodeEditor.onSelectionChanged(CodeEditor.java:4121)
	at io.github.rosemoe.sora.widget.CodeEditor.afterDelete(CodeEditor.java:4634)
	at io.github.rosemoe.sora.text.Content.dispatchAfterDelete(Content.java:1001)
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:532)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:448)
	at io.github.rosemoe.sora.text.UndoManager$InsertAction.undo(UndoManager.java:424)
	at io.github.rosemoe.sora.text.UndoManager.undo(UndoManager.java:136)
	at io.github.rosemoe.sora.text.Content.undo(Content.java:582)
	at io.github.rosemoe.sora.widget.CodeEditor.undo(CodeEditor.java:2338)
	at com.itsaky.androidide.actions.text.UndoAction.execAction(UndoAction.kt:50)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction$lambda$4(DefaultActionsRegistry.kt:180)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$dXsASD5DI7x0X3S7AhqTqILaCV8(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction(DefaultActionsRegistry.kt:179)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda$3(DefaultActionsRegistry.kt:169)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$PPRxnA5HN5W60216J1ZeVbR5hrk(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda3.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
	at android.view.View.performClick(View.java:7570)
	at android.view.View.performClickInternal(View.java:7540)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29710)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8374)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in Rosemoe/sora-editor@3558f2f.
