### ISSUE TITLE
[Bug]: The project is not going

### ISSUE THREAD

**Issue by relyaf** [AndroidIDEOfficial/AndroidIDE#1235]
### What happened?

It seems that everything is ok, but no, I click on the build of the project and I get errors in the log ide.

# Do not close explain what the problem is or if there is such a problem, throw off the link :^

### What's the expected behavior?

I think it's clear that I'm waiting for the assembly of the Kotlin application

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
Ide logs:

EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
DefaultActionsRegistry    I   Action 'ide.editor.build.quickRun' completed in 27ms 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
EditorActivity            D   Is project initialized: true 
EditorActivity            D   Sending init request to tooling server.. 
GradleBuildService        W   A build is already in progress! 
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectMessage(directory=/storage/emulated/0/AndroidIDEProjects, gradleInstallation=)  
ToolingApiErrorStream     E   Aug 29, 2023 12:20:11 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError 
ToolingApiErrorStream     E   SEVERE: Internal error: java.lang.IllegalStateException: Project is not initialized! 
ToolingApiErrorStream     E   java.util.concurrent.CompletionException: java.lang.IllegalStateException: Project is not initialized! 
ToolingApiErrorStream     E   	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl.assertProjectInitialized(ToolingApiServerImpl.kt:277) 
ToolingApiErrorStream     E   	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl.executeTasks$lambda$4(ToolingApiServerImpl.kt:143) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) 
ToolingApiErrorStream     E   Caused by: java.lang.IllegalStateException: Project is not initialized! 
ToolingApiErrorStream     E   	... 9 more 
ToolingApiErrorStream     E    
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
QuickRunAction            E   Tasks failed to execute  assembleDebug 
QuickRunAction            D   Cannot install APK. Task execution result:  null 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 322ms  
ToolingApiServer          D   StopWatch                  Project connection established in 193ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          E   ToolingApiServerImpl      
ToolingApiServer          E  java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.gradle.org/distributions/gradle-7.4.2-bin.zip
ToolingApiServer          E  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
ToolingApiServer          E  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
ToolingApiServer          E  	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
ToolingApiServer          E  	at org.gradle.wrapper.Download.downloadInternal(Download.java:109)
ToolingApiServer          E  	at org.gradle.wrapper.Download.download(Download.java:89)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DistributionInstaller$AsyncDownload$1.run(DistributionInstaller.java:182)
ToolingApiServer          E   Caused by: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:135)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:41)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:44)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:160)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:142)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:67)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.util.ProjectReader.read(ProjectReader.java:107)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl.initialize$lambda$0(ToolingApiServerImpl.kt:109)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
ToolingApiServer          E  
ToolingApiServer          E   
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
EditorActivity            D   [onPause]  No opened files.  Opened files cache reset to null. 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 

Why is it? because as a result of the assembly there is nothing
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Seems like an issue with your network connection. I am able to download that Gradle distribution from that specific URL.

**Comment by relyaf** [comment]
@itsaky, I do not get you :<

**Comment by frog-o** [comment]
This maybe of no use ,What I found interesting it says a build is already in progress.  And project isn't initialized yet.  I am not an expert but that doesn't seem right did you clean the build and try building again.
