### ISSUE TITLE
[BUG]   Null pointer caused by Android killing background

### ISSUE THREAD

**Issue by eirv** [AndroidIDEOfficial/AndroidIDE#124]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote8Pro
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.itsaky.androidide.models.XMLAttribute.getValue()' on a null object reference
	at com.itsaky.androidide.fragments.attr.AbstractReferenceEditor.setupReferenceInput(AbstractReferenceEditor.java:58)
	at com.itsaky.androidide.fragments.attr.ReferenceEditor.onViewCreated(ReferenceEditor.java:56)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8173)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3602)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```
https://user-images.githubusercontent.com/64970244/158633652-8e33c598-cf8e-4377-ab6d-9ea812b29757.mp4

**Comment by mikofe** [comment]
Termux:
su
am kill com.itsaky.androidide

Simulate Android killing background
