### ISSUE TITLE
[Bug]: AIDE Crashed

### ISSUE THREAD

**Issue by relyaf** [AndroidIDEOfficial/AndroidIDE#1241]
### What happened?

I wanted to close the project, but I came across this message and decided to let you know, maybe it will help you :)

### What's the expected behavior?

._. ?

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A125F
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:20)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5122)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@670d302: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5142)
	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please upgrade to the latest version of AndroidIDE.
