### ISSUE TITLE
Bug...

### ISSUE THREAD

**Issue by Safacts** [AndroidIDEOfficial/AndroidIDE#1273]
### What happened?

Got crashed while opening a existing project file

### What's the expected behavior?

Should open a file of project 

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: POCOM2Pro
ABI: arm64-v8a
SDK version: 31
App version: v2.5.1-beta (251)

 Stacktrace: 
android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:12903)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2320)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2559)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)

	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:12903)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2320)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2559)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)
 Caused by: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 4027, callerPackage: com.itsaky.androidide
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5776)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1780)
	at android.app.ContextImpl.registerReceiverAsUser(ContextImpl.java:1755)
	at android.content.ContextWrapper.registerReceiverAsUser(ContextWrapper.java:775)
	at android.content.ContextWrapper.registerReceiverAsUser(ContextWrapper.java:775)
	at android.widget.ViewFlipper.onAttachedToWindow(ViewFlipper.java:103)
	at android.view.View.dispatchAttachedToWindow(View.java:21092)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5307)
	at android.view.ViewGroup.addView(ViewGroup.java:5093)
	at android.view.ViewGroup.addView(ViewGroup.java:5030)
	at android.view.ViewGroup.addView(ViewGroup.java:5002)
	at com.unnamed.b.atv.view.AndroidTreeView.expandNode(Unknown Source:76)
	at com.itsaky.androidide.fragments.FileTreeFragment.expandNode(Unknown Source:27)
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:393)
	at com.itsaky.androidide.fragments.FileTreeFragment$listNode$2.complete(Unknown Source:4)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:857)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you provide a way to reproduce this issue? Also, upgrade to the latest version of AndroidIDE.
