### ISSUE TITLE
[Bug]: Problems with autocomplete

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#1281]
### What happened?

When installing the latest debug I noticed that there are problems with autocompletion, while you write the code the suggestions are not shown, sometimes it is a total or partial loss of autocompletion.

I'm using commit `42ac697` 

### What's the expected behavior?

show autocomplete suggestions while writing code

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ask9027** [comment]
after this commit `47ecf43` , auto complete not working as expected.

**Comment by esalessandrxx** [comment]
> > No, it doesn't work on my device, I have the latest debug and many times the autocomplete stops working while you write the code.
> > Example:
> > ![Screenshot_20230919_125232_AndroidIDE](https://user-images.githubusercontent.com/117092624/269036052-f934e2c7-25d8-49e5-baf7-1280c406f8af.jpg) `image1:` First letter typed, autocomplete works.
> > ![Screenshot_20230919_125243_AndroidIDE](https://user-images.githubusercontent.com/117092624/269036175-e36b7004-08ab-465d-b4b2-e0cf56349470.jpg) `image2:` The rest of the code no longer shows autocomplete
> 
> Did you test it at [47ecf43](https://github.com/AndroidIDEOfficial/AndroidIDE/commit/47ecf43b9c94805c7991ddfdc3a1a431df2815c1) build apk from github action #1567

but that is a confirmation from two weeks ago, it doesn't work in the last one, isn't it correct that it works in the last debug? Otherwise I would continue using the release version, as I have had to do.

**Comment by itsaky** [comment]
The above commit should fix the issue. Try out the [latest CI build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/6290706455) and let me know if the issue still occurs. If it does, please reopen this issue.

**Comment by esalessandrxx** [comment]
> La confirmación anterior debería solucionar el problema. Pruebe la [última versión de CI](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/6290706455) y avíseme si el problema persiste. Si es así, vuelva a abrir este problema.

Thanks, I'll try. 😊

**Comment by esalessandrxx** [comment]
> The above commit should fix the issue. Try out the [latest CI build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/6290706455) and let me know if the issue still occurs. If it does, please reopen this issue.

Thanks, I'll try. 😊

**Comment by ask9027** [comment]
ya, working but first response is very slow or not show at first time but after some time or retype again , then it show relative autocomplete.

after this commit there is no option to `format code`
![Screenshot_2023-09-24-20-55-36-082_com itsaky androidide-edit](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/61283438/f045e252-b955-4648-89c3-be1fb9d528b9)

**Comment by BanDroid** [comment]
> after this commit there is no option to `format code`
> ![Screenshot_2023-09-24-20-55-36-082_com itsaky androidide-edit](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/61283438/f045e252-b955-4648-89c3-be1fb9d528b9)
>  

try to select first, or select all to format whole file

**Comment by ask9027** [comment]
not showing format option.

![Screenshot_2023-09-24-21-09-53-817_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/61283438/ad5d77a5-3c2e-4c32-90ba-c127f52dece6)

does ide auto format code?

**Comment by esalessandrxx** [comment]
If you select the code if it is formatted, but for some reason it is not complete, the example below formats everything except `if(Build.VERSION.SDK_INT`

![screenshots](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/117092624/ef6931c3-d72c-445d-9f64-03435a0f7540)

**Comment by ask9027** [comment]
ya, format code option is showing while swipe to left.

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/61283438/e894be1d-34a7-4f11-98a1-a999790c1498


but format code not woking.
```
JavaCodeFormatProvider    E   Failed to format code. 
JavaCodeFormatProvider    E  com.google.googlejavaformat.java.FormatterException: 3:2: error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/Streams;
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.splitModifiers(JavaInputAstVisitor.java:3400)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitModifiers(JavaInputAstVisitor.java:2494)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitModifiers(JavaInputAstVisitor.java:2480)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.typeDeclarationModifiers(JavaInputAstVisitor.java:2469)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitEnumDeclaration(JavaInputAstVisitor.java:2255)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:569)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:170)
JavaCodeFormatProvider    E  	at openjdk.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:874)
JavaCodeFormatProvider    E  	at openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:86)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:2098)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitCompilationUnit(JavaInputAstVisitor.java:517)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitCompilationUnit(JavaInputAstVisitor.java:170)
JavaCodeFormatProvider    E  	at openjdk.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:616)
JavaCodeFormatProvider    E  	at openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:86)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:2098)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:264)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:206)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.lsp.java.providers.CodeFormatProvider.format(CodeFormatProvider.java:76)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.lsp.java.JavaLanguageServer.formatCode(JavaLanguageServer.java:263)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.editor.language.LSPFormatter.doFormat(LSPFormatter.kt:66)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.editor.language.LSPFormatter.doFormat$default(LSPFormatter.kt:50)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.editor.language.LSPFormatter.formatAsync(LSPFormatter.kt:39)
JavaCodeFormatProvider    E  	at io.github.rosemoe.sora.lang.format.AsyncFormatter$FormattingThread.run(AsyncFormatter.java:178)
JavaCodeFormatProvider    E  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.collect.Streams" on path: DexPathList[[zip file "/data/app/~~eE2aKqYFvOlkufqVUw0nCQ==/com.itsaky.androidide-B8Gtc0eFQnOFIwCSWopsdw==/base.apk"],nativeLibraryDirectories=[/data/app/~~eE2aKqYFvOlkufqVUw0nCQ==/com.itsaky.androidide-B8Gtc0eFQnOFIwCSWopsdw==/lib/arm64, /data/app/~~eE2aKqYFvOlkufqVUw0nCQ==/com.itsaky.androidide-B8Gtc0eFQnOFIwCSWopsdw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
JavaCodeFormatProvider    E  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
JavaCodeFormatProvider    E  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
JavaCodeFormatProvider    E  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
JavaCodeFormatProvider    E  	... 23 more
JavaCodeFormatProvider    E  
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.splitModifiers(JavaInputAstVisitor.java:3400)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitModifiers(JavaInputAstVisitor.java:2494)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitModifiers(JavaInputAstVisitor.java:2480)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.typeDeclarationModifiers(JavaInputAstVisitor.java:2469)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitEnumDeclaration(JavaInputAstVisitor.java:2255)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:569)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:170)
JavaCodeFormatProvider    E  	at openjdk.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:874)
JavaCodeFormatProvider    E  	at openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:86)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:2098)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitCompilationUnit(JavaInputAstVisitor.java:517)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitCompilationUnit(JavaInputAstVisitor.java:170)
JavaCodeFormatProvider    E  	at openjdk.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:616)
JavaCodeFormatProvider    E  	at openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:86)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:2098)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:264)
JavaCodeFormatProvider    E  	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:206)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.lsp.java.providers.CodeFormatProvider.format(CodeFormatProvider.java:76)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.lsp.java.JavaLanguageServer.formatCode(JavaLanguageServer.java:263)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.editor.language.LSPFormatter.doFormat(LSPFormatter.kt:66)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.editor.language.LSPFormatter.doFormat$default(LSPFormatter.kt:50)
JavaCodeFormatProvider    E  	at com.itsaky.androidide.editor.language.LSPFormatter.formatAsync(LSPFormatter.kt:39)
JavaCodeFormatProvider    E  	at io.github.rosemoe.sora.lang.format.AsyncFormatter$FormattingThread.run(AsyncFormatter.java:178)
```
