### ISSUE TITLE
[Bug]: App doesn't work on user 10 side of android 8.1 mtk device

### ISSUE THREAD

**Issue by asadullahibnrob** [AndroidIDEOfficial/AndroidIDE#1308]
### What happened?

I have multiple user accounts on my device. The developer account is on user 10. Create another user by typing "su", "pm create-user developer". When I open the app it gives error pasted below.

### What's the expected behavior?

To create a folder

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: TINNO
Device: U318AA
ABI: armeabi-v7a
SDK version: 27
App version: v2.5.3-beta (253)

 Stacktrace: 
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:418)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:421)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1661)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1653)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Thanks for the report. I'll look into it.

**Comment by itsaky** [comment]
Hey @asadullahibnrob,

I totally forgot that multiple users are not supported at the moment. This is a limitation for the terminal packages as the path `/data/data/com.itsaky.androidide` is hardcoded in the binaries.
