### ISSUE TITLE
Error al compilar desde android 10 usando vpn [Bug]: 

### ISSUE THREAD

**Issue by LonySystemGosh** [AndroidIDEOfficial/AndroidIDE#1312]
### What happened?

AndroidIDE crash report
Manufacturer: TCL
Device: 5002A
ABI: armeabi-v7a
SDK version: 29
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1949)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

### What's the expected behavior?

La aplicación se craseha

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Upgrade to the version of AndroidIDE.
