### ISSUE TITLE
[Bug]: App Crashed

### ISSUE THREAD

**Issue by sourav-kum** [AndroidIDEOfficial/AndroidIDE#1317]
### What happened?

App Crashed While Typeing.

### What's the expected behavior?

It should not crash.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A346E
ABI: arm64-v8a
SDK version: 34
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index 14 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at io.github.rosemoe.sora.widget.CodeEditor.binarySearchEndBlock(Unknown Source:27)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(Unknown Source:1857)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(Unknown Source:33)
	at android.view.View.draw(View.java:25132)
	at android.view.View.updateDisplayListIfDirty(View.java:23991)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23937)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23937)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23937)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23937)
	at android.view.View.draw(View.java:24862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(Unknown Source:13)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at android.view.View.updateDisplayListIfDirty(View.java:23977)
	at android.view.View.draw(View.java:24862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(Unknown Source:103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at android.view.View.updateDisplayListIfDirty(View.java:23977)
	at android.view.View.draw(View.java:24862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at android.view.View.updateDisplayListIfDirty(View.java:23977)
	at android.view.View.draw(View.java:24862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at android.view.View.updateDisplayListIfDirty(View.java:23977)
	at android.view.View.draw(View.java:24862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at android.view.View.updateDisplayListIfDirty(View.java:23977)
	at android.view.View.draw(View.java:24862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at android.view.View.updateDisplayListIfDirty(View.java:23977)
	at android.view.View.draw(View.java:24862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1166)
	at android.view.View.draw(View.java:25135)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1148)
	at android.view.View.updateDisplayListIfDirty(View.java:23991)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:722)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:728)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:826)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5860)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5529)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4655)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3171)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11022)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1602)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1611)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1108)
	at android.view.Choreographer.doFrame(Choreographer.java:1038)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1575)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8881)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in v2.6.0-beta.
