### ISSUE TITLE
[Bug]: Unexpected closure 

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#1339]
### What happened?

Exiting AndroidIDE repeatedly and going to another application, for example, and then returning to AndroidIDE causes it to close. If I remember correctly, this error had already been solved.

### What's the expected behavior?

being able to enter and exit the application without problems.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 73be7f525
Variant : arm64-v8a (debug)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-G781V

Stacktrace:
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.itsaky.androidide.services.builder.GradleServiceBinder
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:36)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2348)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2381)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BanDroid** [comment]
what you're doing here is not exit androidide, but make androidide in opened recent apps and running in background, the state is reset by your device power manager, try to disable battery optimization for androidide in your app settings

**Comment by esalessandrxx** [comment]
> what you're doing here is not exit androidide, but make androidide in opened recent apps and running in background, the state is reset by your device power manager, try to disable battery optimization for androidide in your app settings

Yes, by exiting the application I mean that, putting it in the background to go to another application. I'll try what you recommend, thanks.
