### ISSUE TITLE
[Bug]: App Crashed when using Symbols 

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1342]
### What happened?

When i clicked on semicolon it didn't work so i thought its lagging but when i try clicking on other symbols than it crashed

### What's the expected behavior?

.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G965F
ABI: arm64-v8a
SDK version: 29
App version: v2.5.1-beta (251)

 Stacktrace: 
java.lang.IllegalStateException: Cannot access native object
	at com.itsaky.androidide.treesitter.TSNativeObject.checkAccess(Unknown Source:11)
	at com.itsaky.androidide.treesitter.TSQuery.getPatternCount(Unknown Source:0)
	at okhttp3.internal.ws.RealWebSocket$$ExternalSyntheticLambda0.run(Unknown Source:79)
	at androidx.lifecycle.ViewModelProvider.runOnUiThread(Unknown Source:27)
	at io.github.rosemoe.sora.widget.EditorSearcher$$ExternalSyntheticLambda0.onReceive(Unknown Source:103)
	at io.github.rosemoe.sora.event.EventManager.dispatchEvent(Unknown Source:89)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelection(SourceFile:8)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelection(SourceFile:1)
	at com.unnamed.b.atv.view.AndroidTreeView$$ExternalSyntheticLambda0.onClick(Unknown Source:459)
	at android.view.View.performClick(View.java:7862)
	at android.widget.TextView.performClick(TextView.java:15004)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Try using the latest version of AndroidIDE. There were a few related improvements to the editor as well as android-tree-sitter after v2.5.1-beta.

**Comment by CyberXCoder-6649** [comment]
> Try using the latest version of AndroidIDE. There were a few related improvements to the editor as well as android-tree-sitter after v2.5.1-beta.

Okay
