### ISSUE TITLE
[Bug]: Crased

### ISSUE THREAD

**Issue by extronteam** [AndroidIDEOfficial/AndroidIDE#1350]
### What happened?

AndroidIDE crash report
Manufacturer: vivo
Device: V2065
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:20)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5001)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@9c9be81: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5021)
	at android.app.ActivityThread.access$2400(ActivityThread.java:284)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2327)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8396)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: vivo
Device: V2065
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:20)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5001)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@9c9be81: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5021)
	at android.app.ActivityThread.access$2400(ActivityThread.java:284)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2327)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8396)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

### What version of AndroidIDE you're using?

v2.5.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Upgrade to the latest version of AndroidIDE.
