### ISSUE TITLE
[Bug]: .java file Crash  

### ISSUE THREAD

**Issue by AKarchi** [AndroidIDEOfficial/AndroidIDE#1370]
### What happened?

MainActvity.java file does not work. All codes have a red underline.

### What's the expected behavior?

...

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: vivo
Device: V2134
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:20)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4983)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@2d55e7b: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5003)
	at android.app.ActivityThread.access$2400(ActivityThread.java:284)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Upgrade to the latest version of AndroidIDE.
