### ISSUE TITLE
🤷‍♂️

### ISSUE THREAD

**Issue by CPAKO3ABP** [AndroidIDEOfficial/AndroidIDE#1375]
AndroidIDE crash report
Manufacturer: Xiaomi
Device: MI8UD
ABI: arm64-v8a
SDK version: 29
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.remove(Unknown Source:44)
	at com.itsaky.androidide.uidesigner.adapters.ViewAttrListAdapter$$ExternalSyntheticLambda1.onClick(Unknown Source:35)
	at androidx.preference.PreferenceFragmentCompat$1.handleMessage(Unknown Source:45)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)

**Comment by itsaky** [comment]
You can at least give a proper title to the issue. Also, provide a way to reproduce this error.

**Comment by frknkrc44** [comment]
@itsaky Maybe from this code https://github.com/AndroidIDEOfficial/AndroidIDE/blob/08c1444/uidesigner/src/main/java/com/itsaky/androidide/uidesigner/adapters/ViewAttrListAdapter.kt#L96 because this line contains the index number instead of the attribute.
