### ISSUE TITLE
stacktrace

### ISSUE THREAD

**Issue by JPDeveloperr** [AndroidIDEOfficial/AndroidIDE#1379]
bug using the physical keyboard, after typing the ˜ key

AndroidIDE crash report
Manufacturer: samsung
Device: SM-A307GT
ABI: arm64-v8a
SDK version: 30
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.IllegalArgumentException
	at java.lang.Character.toChars(Character.java:5207)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(Unknown Source:1240)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3624)
	at android.view.View.dispatchKeyEvent(View.java:15050)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:903)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1947)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4142)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(Unknown Source:0)
	at com.google.common.io.Files.dispatchKeyEvent(Unknown Source:10)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(Unknown Source:18)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(Unknown Source:22)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent$androidx$appcompat$view$WindowCallbackWrapper(Unknown Source:2)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(Unknown Source:19)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:758)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7365)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7191)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6819)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7007)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3624)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3163)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3154)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3601)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by itsaky** [comment]
Please report this to the [sora-editor](https://github.com/Rosemoe/sora-editor) repo.
