### ISSUE TITLE
Error on terminal 

### ISSUE THREAD

**Issue by aquilesTrindade** [AndroidIDEOfficial/AndroidIDE#1384]
### What happened?

Error on open terminal 

### What's the expected behavior?

Open terminal

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A205G
ABI: arm64-v8a
SDK version: 30
App version: v2.5.3-beta (253)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:926)
	at android.content.res.AssetManager.open(AssetManager.java:903)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1666)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Download and install the arm64-v8a variant of AndroidIDE.
