### ISSUE TITLE
[Bug]: Error while typing.

### ISSUE THREAD

**Issue by sourav-kum** [AndroidIDEOfficial/AndroidIDE#1386]
### What happened?

It show a error while I am writing the code.

### What's the expected behavior?

It show a error while I am writing the code.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 1d67056f3
Variant : arm64-v8a (debug)
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A346E

Stacktrace:
java.lang.RuntimeException: no method
	at com.itsaky.androidide.lsp.java.utils.FindHelper.findMethod(FindHelper.java:76)
	at com.itsaky.androidide.lsp.java.providers.SignatureProvider.addSourceInfo(SignatureProvider.java:255)
	at com.itsaky.androidide.lsp.java.providers.SignatureProvider.lambda$signatureHelp$0$com-itsaky-androidide-lsp-java-providers-SignatureProvider(SignatureProvider.java:108)
	at com.itsaky.androidide.lsp.java.providers.SignatureProvider$$ExternalSyntheticLambda0.invoke(Unknown Source:8)
	at com.itsaky.androidide.lsp.java.compiler.SynchronizedTask.get(SynchronizedTask.java:81)
	at com.itsaky.androidide.lsp.java.providers.SignatureProvider.signatureHelp(SignatureProvider.java:97)
	at com.itsaky.androidide.lsp.java.providers.SignatureProvider.signatureHelp(SignatureProvider.java:84)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(JavaLanguageServer.kt:212)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$1.invokeSuspend(IDEEditor.kt:388)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### Duplicate issues

- [x] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in v2.6.0-beta.
