### ISSUE TITLE
The code that I wrote for a long time is gone like this

### ISSUE THREAD

**Issue by Demon-nw** [AndroidIDEOfficial/AndroidIDE#1388]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: 22011211C
ABI: arm64-v8a
SDK version: 33
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'int io.github.rosemoe.sora.lang.styling.CodeBlock.endLine' on a null object reference in method 'int io.github.rosemoe.sora.widget.CodeEditor.findCursorBlock()'
	at io.github.rosemoe.sora.widget.CodeEditor.findCursorBlock(Unknown Source:57)
	at io.github.rosemoe.sora.widget.CodeEditor.setStyles(Unknown Source:6)
	at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda0.run(Unknown Source:132)
	at io.github.rosemoe.sora.widget.CodeEditor$$ExternalSyntheticLambda0.run(Unknown Source:24)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

**Comment by itsaky** [comment]
Fixed in Rosemoe/sora-editor#498.
