### ISSUE TITLE
[Bug]: Crash in latest debug build

### ISSUE THREAD

**Issue by DevKumar00001** [AndroidIDEOfficial/AndroidIDE#1397]
### What happened?

Occured while writing an if condition in editor

### What's the expected behavior?

It should not crash

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : f61b15039
Variant : armeabi-v7a (debug)
SDK Version : 29
Supported ABIs : [armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2006C3MII

Stacktrace:
java.lang.ArrayIndexOutOfBoundsException: index = 0, length = 0
	at io.github.rosemoe.sora.util.BlockIntList.set(BlockIntList.java:201)
	at io.github.rosemoe.sora.widget.layout.LineBreakLayout.afterInsert(LineBreakLayout.java:149)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(CodeEditor.java:4764)
	at io.github.rosemoe.sora.text.Content.dispatchAfterInsert(Content.java:1032)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:410)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:350)
	at com.itsaky.androidide.editor.ui.IDEEditor.append(IDEEditor.kt:313)
	at com.itsaky.androidide.fragments.output.LogViewFragment.append$lambda$3$lambda$2(LogViewFragment.kt:167)
	at com.itsaky.androidide.fragments.output.LogViewFragment.$r8$lambda$_VYTa4RgilJNMb9kv95bZZS8Dno(Unknown Source:0)
	at com.itsaky.androidide.fragments.output.LogViewFragment$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in cc874da0f.
