### ISSUE TITLE
[Bug]: error while typing 

### ISSUE THREAD

**Issue by someonespcl** [AndroidIDEOfficial/AndroidIDE#1400]
### What happened?

Crashed while typing 

### What's the expected behavior?

It should not to be crash 

### What version of AndroidIDE you're using?

v2.5.3

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2101K7AI
ABI: arm64-v8a
SDK version: 31
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.IllegalStateException: Cannot access native object
	at com.itsaky.androidide.treesitter.TSNativeObject.checkAccess(Unknown Source:11)
	at com.itsaky.androidide.treesitter.TSQuery.getPatternCount(Unknown Source:0)
	at okhttp3.internal.ws.RealWebSocket$$ExternalSyntheticLambda0.run(Unknown Source:79)
	at androidx.lifecycle.ViewModelProvider.runOnUiThread(Unknown Source:27)
	at io.github.rosemoe.sora.widget.EditorSearcher$$ExternalSyntheticLambda0.onReceive(Unknown Source:103)
	at io.github.rosemoe.sora.event.EventManager.dispatchEvent(Unknown Source:89)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelection(SourceFile:8)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelection(SourceFile:1)
	at com.unnamed.b.atv.view.AndroidTreeView$$ExternalSyntheticLambda0.onClick(Unknown Source:459)
	at android.view.View.performClick(View.java:7753)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:858)
	at android.view.View$PerformClick.run(View.java:29126)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8302)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in recent commits.
