### ISSUE TITLE
[Bug]: Crash while editing

### ISSUE THREAD

**Issue by AozoraDev** [AndroidIDEOfficial/AndroidIDE#1402]
### What happened?

Im just typing my code like usual while eating McD Double Cheese burger with extra pickles, and then suddenly the app crash.

### What's the expected behavior?

Uhm... No crash?

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 42ae28a0b
Variant : arm64-v8a (debug)
SDK Version : 27
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : vivo1820

Stacktrace:
java.lang.NullPointerException
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.updateStyles(TsAnalyzeWorker.kt:195)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.access$updateStyles(TsAnalyzeWorker.kt:48)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker$doMod$3.invokeSuspend(TsAnalyzeWorker.kt:179)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AozoraDev** [comment]
There's another
```

AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 42ae28a0b
Variant : arm64-v8a (debug)
SDK Version : 27
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : vivo1820

Stacktrace:
java.lang.IndexOutOfBoundsException: index 1375 out of bounds, size = 1373
	at com.itsaky.androidide.treesitter.string.Assertions.checkIndex(Assertions.java:34)
	at com.itsaky.androidide.treesitter.string.UTF16String.subseqChars(UTF16String.java:204)
	at io.github.rosemoe.sora.editor.ts.predicate.builtin.UtilsKt.getCaptureContent(Utils.kt:57)
	at com.itsaky.androidide.editor.language.treesitter.predicates.MatchPredicate.doPredicateInternal$editor_debug(MatchPredicate.kt:60)
	at com.itsaky.androidide.editor.language.treesitter.predicates.TreeSitterPredicate.doPredicate(TreeSitterPredicate.kt:79)
	at io.github.rosemoe.sora.editor.ts.predicate.Predicator.doPredicate(Predicator.kt:81)
	at io.github.rosemoe.sora.editor.ts.predicate.Predicator.doPredicate$default(Predicator.kt:63)
	at io.github.rosemoe.sora.editor.ts.TsScopedVariables$1$2.invoke(TsScopedVariables.kt:85)
	at io.github.rosemoe.sora.editor.ts.TsScopedVariables$1$2.invoke(TsScopedVariables.kt:76)
	at com.itsaky.androidide.treesitter.api.TsUtilsKt.doSafeExecQueryCursor(tsUtils.kt:143)
	at com.itsaky.androidide.treesitter.api.TsUtilsKt.safeExecQueryCursor(tsUtils.kt:100)
	at com.itsaky.androidide.treesitter.api.TsUtilsKt.safeExecQueryCursor(tsUtils.kt:62)
	at com.itsaky.androidide.treesitter.api.TsUtilsKt.safeExecQueryCursor$default(tsUtils.kt:37)
	at io.github.rosemoe.sora.editor.ts.TsScopedVariables.<init>(TsScopedVariables.kt:76)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.updateStyles(TsAnalyzeWorker.kt:196)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.access$updateStyles(TsAnalyzeWorker.kt:48)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker$doMod$3.invokeSuspend(TsAnalyzeWorker.kt:179)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

 ```

**Comment by itsaky** [comment]
Fixed in recent commits.
