### ISSUE TITLE
[Bug] Highlighting Reset when Code Formated

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1403]
### What happened?

When Clicked on Format it just loses Highlighted Colors to Full Color
### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
TsAnalyzeWorker           E   AnalyzeWorker[lang=java, pendingMsgs=0] crashed 
TsAnalyzeWorker           E  java.lang.IllegalStateException: 'Init' must be the first message to TsAnalyzeWorker
TsAnalyzeWorker           E  	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.doMod(TsAnalyzeWorker.kt:137)
TsAnalyzeWorker           E  	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.processNextMessage(TsAnalyzeWorker.kt:114)
TsAnalyzeWorker           E  	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.access$processNextMessage(TsAnalyzeWorker.kt:48)
TsAnalyzeWorker           E  	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker$processNextMessage$1.invokeSuspend(Unknown Source:15)
TsAnalyzeWorker           E  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
TsAnalyzeWorker           E  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
TsAnalyzeWorker           E  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
TsAnalyzeWorker           E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
TsAnalyzeWorker           E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
TsAnalyzeWorker           E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
TsAnalyzeWorker           E  
TsAnalyzeWorker           E
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in 6ba102b6099035719728bb5c216188f7ab20472f.
