### ISSUE TITLE
[Bug]: Error while typing

### ISSUE THREAD

**Issue by sourav-kum** [AndroidIDEOfficial/AndroidIDE#1407]
### What happened?

It crashed and show error while typing

### What's the expected behavior?

It crashed and show error while typing

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : fba140e85
Variant : arm64-v8a (debug)
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A346E

Stacktrace:
java.lang.ArrayIndexOutOfBoundsException: length=20; index=-1
	at io.github.rosemoe.sora.util.Numbers.getChars(Numbers.java:104)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawLineNumber(EditorRenderer.java:977)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawStuckLineNumbers(EditorRenderer.java:797)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:749)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:201)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4325)
	at android.view.View.draw(View.java:25148)
	at android.view.View.updateDisplayListIfDirty(View.java:24007)
	at android.view.View.draw(View.java:24878)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4776)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4534)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.updateDisplayListIfDirty(View.java:23993)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4760)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4732)
	at android.view.View.updateDisplayListIfDirty(View.java:23953)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:764)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:770)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:868)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5944)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5613)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4733)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3238)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11188)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
	at android.view.Choreographer.doFrame(Choreographer.java:1055)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please report this to [sora-editor](https://github.com/Rosemoe/sora-editor) with steps to reproduce this issue.
