### ISSUE TITLE
[Bug]: Crashes after project building

### ISSUE THREAD

**Issue by arunbhattarai** [AndroidIDEOfficial/AndroidIDE#1411]
### What happened?

AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 58c356203
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-G998B

Stacktrace:
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at com.itsaky.androidide.projects.classpath.JarFsClasspathReader$listClasses$2.visitFile(Unknown Source:145)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at androidx.room.AutoCloser$Companion.listClasses(Unknown Source:131)
	at com.itsaky.androidide.projects.ProjectManagerImpl$setupProject$4$jobs$1$1.invokeSuspend(Unknown Source:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)

    

### What's the expected behavior?

IDE should crash after project build successfully.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you list the dependencies that you are using in your project?

**Comment by arunbhattarai** [comment]
I cloned this project  "https://github.com/KapilYadav-dev/Flixtube.git" and when i build the project,ide get shutdown by throwing stacktrace.
