### ISSUE TITLE
[Bug]: Initial Config Failure

### ISSUE THREAD

**Issue by Git2020104** [AndroidIDEOfficial/AndroidIDE#1415]
### What happened?

AndroidIDE crash report
Manufacturer: HMD Global
Device: NokiaC1Plus
ABI: armeabi-v7a
SDK version: 29
App version: v2.5.2-beta (252)

 Stacktrace: 
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:418)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:421)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

### What's the expected behavior?

Configuration successful

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: HMD Global
Device: NokiaC1Plus
ABI: armeabi-v7a
SDK version: 29
App version: v2.5.2-beta (252)

 Stacktrace: 
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:418)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:421)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Make sure you'e the primary user on the user and AndroidIDE is installed on the internal storage. AndroidIDE cannot be installed for secondary users or on SD cards.

**Comment by Git2020104** [comment]
Oh thanks for the feedback
