### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cumaRull** [AndroidIDEOfficial/AndroidIDE#1416]
### What happened?

AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : 1356/merge
Commit : e1f86ffbd
Variant : arm64-v8a (debug)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-M127F

Stacktrace:
java.lang.NullPointerException
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.updateStyles(TsAnalyzeWorker.kt:195)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.access$updateStyles(TsAnalyzeWorker.kt:48)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker$doMod$3.invokeSuspend(TsAnalyzeWorker.kt:179)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

    

### What's the expected behavior?

AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : 1356/merge
Commit : e1f86ffbd
Variant : arm64-v8a (debug)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-M127F

Stacktrace:
java.lang.NullPointerException
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.updateStyles(TsAnalyzeWorker.kt:195)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.access$updateStyles(TsAnalyzeWorker.kt:48)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker$doMod$3.invokeSuspend(TsAnalyzeWorker.kt:179)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

    

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : 1356/merge
Commit : e1f86ffbd
Variant : arm64-v8a (debug)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-M127F

Stacktrace:
java.lang.NullPointerException
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.updateStyles(TsAnalyzeWorker.kt:195)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker.access$updateStyles(TsAnalyzeWorker.kt:48)
	at io.github.rosemoe.sora.editor.ts.TsAnalyzeWorker$doMod$3.invokeSuspend(TsAnalyzeWorker.kt:179)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Use the latest CI build.
