### ISSUE TITLE
[Bug]: when app is in background 

### ISSUE THREAD

**Issue by someonespcl** [AndroidIDEOfficial/AndroidIDE#1417]
### What happened?

Crashed!!!

### What's the expected behavior?

It should not be crash 

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : cd8d9aa4d
Variant : arm64-v8a (release)
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2101K7AI

Stacktrace:
java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: SymbolInputAdapter$VH{dcca2a7 position=3 id=-1, oldPos=-1, pLpos:-1 tmpDetached no parent} com.itsaky.androidide.ui.SymbolInputView{71cb43c VFED..... .......D 0,0-1080,110 #7f0a0294 app:id/symbol_input}, adapter:com.itsaky.androidide.adapters.SymbolInputAdapter@36376f0, layout:androidx.recyclerview.widget.LinearLayoutManager@23d4236, context:com.itsaky.androidide.activities.editor.EditorActivityKt@b15e215
	at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(Unknown Source:314)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(Unknown Source:87)
	at androidx.recyclerview.widget.DefaultItemAnimator$6.onAnimationEnd(Unknown Source:10)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1112)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:948)
	at android.view.Choreographer.doFrame(Choreographer.java:872)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1129)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8302)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in 420c95b.
