### ISSUE TITLE
[Feature]: Modification of file tree viewer

### ISSUE THREAD

**Issue by arunbhattarai** [AndroidIDEOfficial/AndroidIDE#1419]
### Feature description

@itsaky Can you implement same file view hierarchy as same as android studio where default is set to android view.
1.file tree viewer can be renamed as Project view.
2.The newer project view can have drop down menu.and the options are project files view,android view and so on.
3.when selecting project view,all files should be displayed.
4.when selecting android view files of app module and gradle module should be displayed.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This will be added, eventually. But I can't provide an ETA at the moment.

**Comment by Binodsahu123** [comment]
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2373

Stacktrace:
java.lang.IllegalStateException: Fragment RunTasksDialogFragment{875975d} (49d4ed2f-4a67-4a8e-9126-05f4008d6bf9) not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Unknown Source:15)
	at androidx.fragment.app.DialogFragment.dismissInternal(Unknown Source:89)
	at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(Unknown Source:20)
	at com.itsaky.androidide.actions.build.RunTasksAction.execAction(Unknown Source:4)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$executeAction$1.invokeSuspend(Unknown Source:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)

**Comment by itSMcodez** [comment]
Maybe add file categorization like in android studio. For example, 
1. in android studio you have the themes folder (when you click on it, it shows two files: i.e values.xml and values.xml(night)
2. the gradle folder which when expanded you can see the app level and project level build.gradle files
3. And the other src folders of the app
