### ISSUE TITLE
[Bug]: OOM Error in Editor Activity

### ISSUE THREAD

**Issue by kisonix** [AndroidIDEOfficial/AndroidIDE#1423]
### What happened?

App crashed

### What's the expected behavior?

Not to be crashed...

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 420c95b2c
Variant : armeabi-v7a (debug)
SDK Version : 30
Supported ABIs : [armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 220233L2G

Stacktrace:
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:887)
	at com.itsaky.androidide.editor.ui.EditorCompletionWindow.requireCompletion(EditorCompletionWindow.kt:168)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(CodeEditor.java:4805)
	at io.github.rosemoe.sora.text.Content.dispatchAfterInsert(Content.java:1032)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:410)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:350)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(CodeEditor.java:2003)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:313)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:132)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8097)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Closing in favor of #1694
