### ISSUE TITLE
Crash while coding with RuntimeException: Compiler is already in-use!

### ISSUE THREAD

**Issue by Petersburg2020** [AndroidIDEOfficial/AndroidIDE#1428]
### What happened?

App crashed while I was still coding java and it was building project. I observed that the app crashes anytime I insert a parentheses in some portion of my code.

### What's the expected behavior?

It is expected to not crash. It was expected to only notify me that the code is inconsistent with java standard language.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 420c95b2c
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2239

Stacktrace:
java.lang.RuntimeException: Compiler is already in-use!
	at com.itsaky.androidide.lsp.java.compiler.CompileBatch.<init>(Unknown Source:337)
	at com.itsaky.androidide.lsp.java.compiler.JavaCompilerService.performCompilation(Unknown Source:10)
	at com.itsaky.androidide.lsp.java.compiler.JavaCompilerService.recompile(Unknown Source:12)
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:933)
	at com.itsaky.androidide.lsp.java.compiler.SynchronizedTask.post(Unknown Source:11)
	at com.itsaky.androidide.lsp.java.compiler.CompilerProvider.compile(Unknown Source:50)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(Unknown Source:32)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$1.invokeSuspend(Unknown Source:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I can't reproduce this issue on my device. However, there have been some changes regarding the signature help feature in the editor. Please try the latest version of AndroidIDE and reopen this issue of the problem still exists.
