### ISSUE TITLE
Keeps Crashing when I'm coding displaying IllegalStateException

### ISSUE THREAD

**Issue by Petersburg2020** [AndroidIDEOfficial/AndroidIDE#1429]
### What happened?

Whenever I'm coding and the ide is parsing some java syntax, it just suddenly crash.

### What's the expected behavior?

Parsing of syntax tree should automatically parse the current updated code without crashing.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 420c95b2c
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2239

Stacktrace:
java.lang.IllegalStateException: Parser is already parsing another syntax tree! You must cancel the current parse first!
	at com.itsaky.androidide.treesitter.TSParser$Native.parse(Native Method)
	at com.itsaky.androidide.treesitter.TSParser.parseString(SourceFile:20)
	at com.itsaky.androidide.treesitter.TSParser.parseString(SourceFile:6)
	at com.itsaky.androidide.treesitter.TSParser.parseString(SourceFile:3)
	at com.itsaky.androidide.lsp.java.compiler.JavaCompilerImpl.parse(Unknown Source:297)
	at openjdk.tools.javac.main.JavaCompiler.parse(SourceFile:23)
	at openjdk.tools.javac.main.JavaCompiler.parseFiles(SourceFile:9)
	at openjdk.tools.javac.main.JavaCompiler.parseFiles(SourceFile:1)
	at openjdk.tools.javac.api.JavacTaskImpl.parseInternal(Unknown Source:12)
	at openjdk.tools.javac.api.JavacTaskImpl.$r8$lambda$NyapR5uJzfIp_YTm0DdwUsZ0idA(Unknown Source:0)
	at openjdk.tools.javac.api.JavacTaskImpl$$ExternalSyntheticLambda0.call(Unknown Source:13)
	at openjdk.tools.javac.api.JavacTaskImpl.invocationHelper(Unknown Source:13)
	at openjdk.tools.javac.api.JavacTaskImpl.parse(SourceFile:15)
	at androidx.room.AutoCloser$Companion.process(Unknown Source:12)
	at com.itsaky.androidide.lsp.java.compiler.CompileBatch.<init>(Unknown Source:319)
 Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Parser is already parsing another syntax tree! You must cancel the current parse first!
	at com.itsaky.androidide.lsp.java.compiler.CompileBatch.<init>(Unknown Source:329)
	at com.itsaky.androidide.lsp.java.compiler.JavaCompilerService.performCompilation(Unknown Source:10)
	at com.itsaky.androidide.lsp.java.compiler.JavaCompilerService.recompile(Unknown Source:12)
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:933)
	at com.itsaky.androidide.lsp.java.compiler.SynchronizedTask.post(Unknown Source:11)
	at com.itsaky.androidide.lsp.java.compiler.CompilerProvider.compile(Unknown Source:50)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(Unknown Source:32)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$1.invokeSuspend(Unknown Source:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This has been fixed in da899a7 (AndroidIDEOfficial/android-tree-sitter@8c39b14).
