### ISSUE TITLE
[Bug]: IOOB when removing item selected in 'Additional Gradle Commands' setting

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1444]
### What happened?

When removing the a fifth item in the in the Gradle command dialog the app crashes

Video from user in the group. Error was also reproduced on my side

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/06910672-129b-447a-b603-1a243bbbb295

### What's the expected behavior?

Not crash

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
Stacktrace:
java.lang.IndexOutOfBoundsException: Index: 5, Size: 3
	at java.util.ArrayList.remove(ArrayList.java:503)
	at com.itsaky.androidide.preferences.ChoiceBasedDialogPreference.onSelectionChanged(Unknown Source:20)
	at com.itsaky.androidide.preferences.MultiChoicePreference$$ExternalSyntheticLambda0.onClick(Unknown Source:7)
	at androidx.appcompat.app.AlertController$AlertParams$4.onItemClick(Unknown Source:24)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1235)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3219)
	at android.widget.AbsListView$3.run(AbsListView.java:4312)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment]
Update: I can't remove items already selected:https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/2e499f68-8de9-4941-b1b0-2a25e8e3f96e
