### ISSUE TITLE
[Bug]: The terminal does not work even on the new version of AndroidIDE 2.6.0

### ISSUE THREAD

**Issue by LegionFly24** [AndroidIDEOfficial/AndroidIDE#1450]
### What happened?

I do not know if there is an error or not, I installed this program not long ago, and the terminal does not work here

### What's the expected behavior?

I do not know there is no any behavior

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.0-beta (260)
CI Build : true
Branch : main
Commit : 34d7e34e4
Variant : arm64-v8a (release)
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : RedmiNote7

Stacktrace:
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1498)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1501)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Make sure that you're installing AndroidIDE for the primary user. Multiple users are not supported.
