### ISSUE TITLE
[Bug] Crash when modifying the "Additional Gradle commands"

### ISSUE THREAD

**Issue by hhshaohao** [AndroidIDEOfficial/AndroidIDE#1453]
### What happened?

When I was modifying the "Additional Gradle commands" items, the program crashed

### What's the expected behavior?

No Crash

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.0-beta (260)
CI Build : true
Branch : main
Commit : 34d7e34e4
Variant : arm64-v8a (release)
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : vivoNEXS

Stacktrace:
java.lang.IndexOutOfBoundsException: Index: 5, Size: 4
	at java.util.ArrayList.remove(ArrayList.java:503)
	at com.itsaky.androidide.preferences.ChoiceBasedDialogPreference.onSelectionChanged(Unknown Source:20)
	at com.itsaky.androidide.preferences.MultiChoicePreference$$ExternalSyntheticLambda0.onClick(Unknown Source:7)
	at androidx.appcompat.app.AlertController$AlertParams$4.onItemClick(Unknown Source:24)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1350)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3424)
	at android.widget.AbsListView$3.run(AbsListView.java:4426)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:7987)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment]
This has already been fixed here  https://github.com/AndroidIDEOfficial/AndroidIDE/commit/e5448a4a19cd1c4be22d20afd25d34577562f1ca , download the latest debug version to get the fix
