### ISSUE TITLE
[Bug]: android:sharedUserId causes Thread.currentThread().getContextClassLoader() to change and cannot find resources

### ISSUE THREAD

**Issue by ZeroAicy** [AndroidIDEOfficial/AndroidIDE#1469]
### What happened?

When I add `android:sharedUserId`  to the Android IDE, I cannot find the service interface `com.itsaky.androide.app.IDEBuildConfigProvider.`I found that after adding `android:sharedUserId`  `Thread.currentThread().getContextClassLoader()` will become `android.app.LoadedApk$WarningContextClassLoader.`

### What's the expected behavior?

Should have added `android:sharedUserId`  without flashing back

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
versionName:v2.6.0-beta
versionCode:260
packName:com.itsaky.androidide
Phone model::MEIZU 20 Pro
System version:33
Android version:13
BOARD:kalama
BOOTLOADER:unknown
BRAND:meizu
CPU_ABI:arm64-v8a
CPU_ABI2:
DEVICE:meizu20Pro
DISPLAY:Flyme 10.3.0.0A
FINGERPRINT:meizu/meizu_20Pro_CN/meizu20Pro:13/TKQ1.221114.001/1692864302:user/release-keys
HARDWARE:qcom
HOST:Mz-Builder-L67
HW_TIMEOUT_MULTIPLIER:1
ID:TKQ1.221114.001
IS_ARC:false
IS_DEBUGGABLE:false
IS_EMULATOR:false
IS_ENG:false
IS_TREBLE_ENABLED:true
IS_USER:true
IS_USERDEBUG:false
MANUFACTURER:meizu
MODEL:MEIZU 20 Pro
ODM_SKU:unknown
PERMISSIONS_REVIEW_REQUIRED:true
PRODUCT:meizu_20Pro_CN
RADIO:unknown
SERIAL:unknown
SKU:unknown
SOC_MANUFACTURER:QTI
SOC_MODEL:SM8550
SUPPORTED_32_BIT_ABIS:armeabi-v7a, armeabi, 
SUPPORTED_64_BIT_ABIS:arm64-v8a, 
SUPPORTED_ABIS:arm64-v8a, armeabi-v7a, armeabi, 
TAGS:release-keys
TIME:1699819976000
TYPE:user
UNKNOWN:unknown
USER:flyme
Exception:+
java.lang.ExceptionInInitializerError
	at com.itsaky.androidide.app.BaseApplication.onCreate(Unknown Source:576)
	at com.itsaky.androidide.app.IDEApplication.onCreate(Unknown Source:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6920)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2179)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8062)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: com.itsaky.androidide.utils.ServiceNotFoundException: Cannot find service interface com.itsaky.androidide.app.IDEBuildConfigProvider
	at com.itsaky.androidide.utils.ServiceLoader.findFirstOrThrow(Unknown Source:39)
	at com.itsaky.androidide.preferences.Country$1.invoke(SourceFile:24)
	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
	at com.itsaky.androidide.app.IDEBuildConfigProvider$Companion.getInstance(Unknown Source:2)
	at com.itsaky.androidide.app.IDEBuildConfigProvider.getInstance(Unknown Source:5)
	at com.itsaky.androidide.managers.ToolsManager.<clinit>(Unknown Source:15)
	... 13 more
com.itsaky.androidide.utils.ServiceNotFoundException: Cannot find service interface com.itsaky.androidide.app.IDEBuildConfigProvider
	at com.itsaky.androidide.utils.ServiceLoader.findFirstOrThrow(Unknown Source:39)
	at com.itsaky.androidide.preferences.Country$1.invoke(SourceFile:24)
	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
	at com.itsaky.androidide.app.IDEBuildConfigProvider$Companion.getInstance(Unknown Source:2)
	at com.itsaky.androidide.app.IDEBuildConfigProvider.getInstance(Unknown Source:5)
	at com.itsaky.androidide.managers.ToolsManager.<clinit>(Unknown Source:15)
	at com.itsaky.androidide.app.BaseApplication.onCreate(Unknown Source:576)
	at com.itsaky.androidide.app.IDEApplication.onCreate(Unknown Source:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6920)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2179)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8062)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
You can simply set the context `ClassLoader` in the `IDEApplication` and that should fix the issue :

```kotlin
class IDEApplication {

  override fun onCreate() {
    Thread.currentThread().contextClassLoader = javaClass.classLoader
  }

}
```

I don't think a fix for this is needed in the IDE as we don't use `sharedUserId` ourselves. Even if we start using `sharedUserIds` now, the future builds will be incompatible with existing installation.

**Comment by MrIkso** [comment]
> android:sharedUserId
> This constant is deprecated as of API level 29.
> Shared user IDs cause non-deterministic behavior within the package manager. As such, their use is strongly discouraged and might be removed in a future version of Android. Instead, use proper communication mechanisms, such as services and content providers, to facilitate interoperability between shared components. Existing apps can't remove this value, as migrating off a shared user ID isn't supported. In these apps, add android:sharedUserMaxSdkVersion="32" to avoid using shared user ID on new user installs.

https://developer.android.com/guide/topics/manifest/manifest-element
