### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ArtsphereOfficial** [AndroidIDEOfficial/AndroidIDE#1479]
AndroidIDE Crash Report
Version : v2.6.0-beta (260)
CI Build : true
Branch : main
Commit : 34d7e34e4
Variant : arm64-v8a (release)
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A217F

Stacktrace:
java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
	at java.util.ArrayList.remove(ArrayList.java:503)
	at com.itsaky.androidide.preferences.ChoiceBasedDialogPreference.onSelectionChanged(Unknown Source:20)
	at com.itsaky.androidide.preferences.MultiChoicePreference$$ExternalSyntheticLambda0.onClick(Unknown Source:7)
	at androidx.appcompat.app.AlertController$AlertParams$4.onItemClick(Unknown Source:24)
	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1282)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3528)
	at android.widget.AbsListView$3.run(AbsListView.java:4691)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Rafael2616** [comment]
This isse has already been fixed here e5448a4 , download the latest debug version to get the fix
