### ISSUE TITLE
[Bug]: Crash while inserting two parenthesis very fast

### ISSUE THREAD

**Issue by ThatMG393** [AndroidIDEOfficial/AndroidIDE#1484]
### What happened?

When inserting two '(' (open parenthesis) (either from the bottombar or the keyboard and the state of the project is initiatized or not) at quick succession the application crashes and shows a stacktrace. ~~restarts without any error popup, it just sents me to the MainActivity of the app.~~

### What's the expected behavior?

Normal

### What version of AndroidIDE you're using?

v2.6.0 (debug builds, commit latest)

### Relevant log output

```
com.itsaky.androidide.progress.ProcessCancelledException
	at com.itsaky.androidide.progress.ICancelChecker$Default.abortIfCancelled(Unknown Source:9)
	at com.itsaky.androidide.tasks.JobCancelChecker.abortIfCancelled(Unknown Source:5)
	at com.itsaky.androidide.lsp.java.providers.CancelableServiceProvider.abortIfCancelled(Unknown Source:2)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(Unknown Source:40)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$2.invokeSuspend(Unknown Source:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
In such cases, you need to share the logs files. You can get the logs using the "Dump logs" option in AndroidIDE's Developer Options :

- Open AndroidIDE
- Go to Preferences -> Developer Options and enable "Dump logs"
- Try to reproduce the issue
- Once the issue occurs again, go to preferences and disable "Dump logs"
- Share the corresponding log file located in `$HOME/.androidide/logs` directory.

**Comment by ThatMG393** [comment]
@itsaky I have updated the issue with the logs but according to my observations there's no fatal error in the logs.
