### ISSUE TITLE
[Bug]: Crashes when i edit `Additional Gradle Commands`

### ISSUE THREAD

**Issue by etidoUP** [AndroidIDEOfficial/AndroidIDE#1488]
### What happened?

AndroidIDE Crash Report
Version : v2.6.0-beta (260)
CI Build : true
Branch : main
Commit : 34d7e34e4
Variant : arm64-v8a (release)
SDK Version : 28
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH1923

Stacktrace:
java.lang.IndexOutOfBoundsException: Index: 5, Size: 3
	at java.util.ArrayList.remove(ArrayList.java:503)
	at com.itsaky.androidide.preferences.ChoiceBasedDialogPreference.onSelectionChanged(Unknown Source:20)
	at com.itsaky.androidide.preferences.MultiChoicePreference$$ExternalSyntheticLambda0.onClick(Unknown Source:7)
	at androidx.appcompat.app.AlertController$AlertParams$4.onItemClick(Unknown Source:24)
	at android.widget.AdapterView.performItemClick(AdapterView.java:326)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1206)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3192)
	at android.widget.AbsListView$3.run(AbsListView.java:4284)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:7212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

    

### What's the expected behavior?

It should save the edit but it doesn't.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment]
This issue has already been fixed here e5448a4 , download the latest debug version to get the fix
