### ISSUE TITLE
AndroidIDE Crash Report

### ISSUE THREAD

**Issue by Binodsahu123** [AndroidIDEOfficial/AndroidIDE#1498]
### What happened?

AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2373

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onPause(Unknown Source:11)
	at android.app.Activity.performPause(Activity.java:8584)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1604)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5382)
 Caused by: java.lang.RuntimeException: Unable to pause activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5392)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5343)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5290)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:229)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6063)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2472)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

    

### What's the expected behavior?

AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2373

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onPause(Unknown Source:11)
	at android.app.Activity.performPause(Activity.java:8584)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1604)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5382)
 Caused by: java.lang.RuntimeException: Unable to pause activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5392)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5343)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5290)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:229)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6063)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2472)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

    

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2373

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onPause(Unknown Source:11)
	at android.app.Activity.performPause(Activity.java:8584)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1604)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5382)
 Caused by: java.lang.RuntimeException: Unable to pause activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5392)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5343)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5290)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:229)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6063)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2472)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment]
Context:

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/6e6e22f1-a731-4aa6-b59a-11af589a8b00

**Comment by Binodsahu123** [comment]
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2373

Stacktrace:
java.lang.IllegalStateException: Fragment RunTasksDialogFragment{875975d} (49d4ed2f-4a67-4a8e-9126-05f4008d6bf9) not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Unknown Source:15)
	at androidx.fragment.app.DialogFragment.dismissInternal(Unknown Source:89)
	at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(Unknown Source:20)
	at com.itsaky.androidide.actions.build.RunTasksAction.execAction(Unknown Source:4)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$executeAction$1.invokeSuspend(Unknown Source:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)

**Comment by Rafael2616** [comment]
> 
> AndroidIDE Crash Report
> Version : v2.6.1-beta (261)
> CI Build : true
> Branch : main
> Commit : 8ac221c83
> Variant : arm64-v8a (release)
> SDK Version : 33
> Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
> Manufacturer : OPPO
> Device : CPH2373
> 
> Stacktrace:
> java.lang.IllegalStateException: Fragment RunTasksDialogFragment{875975d} (49d4ed2f-4a67-4a8e-9126-05f4008d6bf9) not associated with a fragment manager.
> 	at androidx.fragment.app.Fragment.getParentFragmentManager(Unknown Source:15)
> 	at androidx.fragment.app.DialogFragment.dismissInternal(Unknown Source:89)
> 	at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(Unknown Source:20)
> 	at com.itsaky.androidide.actions.build.RunTasksAction.execAction(Unknown Source:4)
> 	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$executeAction$1.invokeSuspend(Unknown Source:80)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
> 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
> 
>     

This is not the same issue reported here, could you open a new issue for this?

**Comment by itsvks19** [comment]
Test [this](https://github.com/itsvks19/AndroidIDE/actions/runs/7027362321) build and let me know if it still crashes.
