### ISSUE TITLE
[Bug]: Color scheme crash

### ISSUE THREAD

**Issue by ShuhaibNC** [AndroidIDEOfficial/AndroidIDE#1504]
### What happened?

Crashed while selecting editor color scheme 

### What's the expected behavior?

Select colors scheme 

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OnePlus
Device : DN2103

Stacktrace:
java.lang.IndexOutOfBoundsException: Initial selection: -1, size=0
	at com.itsaky.androidide.preferences.SingleChoicePreference.onConfigureDialogChoices(Unknown Source:48)
	at com.itsaky.androidide.preferences.ChoiceBasedDialogPreference.onConfigureDialog(Unknown Source:48)
	at com.itsaky.androidide.preferences.DialogPreference.onPreferenceClick(Unknown Source:38)
	at org.eclipse.jgit.storage.file.FileBasedConfig$$ExternalSyntheticLambda0.onPreferenceClick(Unknown Source:23)
	at androidx.preference.Preference.performClick(Unknown Source:19)
	at androidx.preference.Preference$1.onClick(Unknown Source:232)
	at android.view.View.performClick(View.java:7558)
	at android.view.View.performClickInternal(View.java:7534)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29661)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8381)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
@ShuhaibNC Unfortunately, I'm unable to reproduce this error. Can you provide steps to reproduce this issue?
