### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1536]
### What happened?

Aftter some time of switching between apps(IDE, browsers),files closed and after few clicks to open em back i could submit this report.

### What's the expected behavior?

Had to open file and stay it.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A202F

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.utils.DialogUtils$$ExternalSyntheticLambda0.onClick(Unknown Source:99)
	at androidx.preference.PreferenceFragmentCompat$1.handleMessage(Unknown Source:59)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Duplicate of #1498.
