### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Ogre777** [AndroidIDEOfficial/AndroidIDE#1539]
### What happened?

AndroidIDE crash report
Manufacturer: LENOVO
Device: LenovoTB-8505X
ABI: arm64-v8a
SDK version: 29
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Unknown Source:9)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsync$2.invoke(SourceFile:26)
	at com.itsaky.androidide.tasks.TaskExecutorKt$sam$com_itsaky_androidide_tasks_TaskExecutor_CallbackWithError$0.complete(Unknown Source:2)
	at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda0.run(Unknown Source:406)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7405)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: LENOVO
Device: LenovoTB-8505X
ABI: arm64-v8a
SDK version: 29
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Unknown Source:9)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsync$2.invoke(SourceFile:26)
	at com.itsaky.androidide.tasks.TaskExecutorKt$sam$com_itsaky_androidide_tasks_TaskExecutor_CallbackWithError$0.complete(Unknown Source:2)
	at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda0.run(Unknown Source:406)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7405)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: LENOVO
Device: LenovoTB-8505X
ABI: arm64-v8a
SDK version: 29
App version: v2.5.0-beta (250)

 Stacktrace: 
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Unknown Source:9)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsync$2.invoke(SourceFile:26)
	at com.itsaky.androidide.tasks.TaskExecutorKt$sam$com_itsaky_androidide_tasks_TaskExecutor_CallbackWithError$0.complete(Unknown Source:2)
	at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda0.run(Unknown Source:406)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7405)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please update to the latest version of AndroidIDE. If the issue exists in the latest version as well, reopen this issue.
