### ISSUE TITLE
[Bug]: Timout reading syntax colors and freezing.

### ISSUE THREAD

**Issue by fluffydaddy** [AndroidIDEOfficial/AndroidIDE#1546]
### What happened?

I opened a 31kb file and started changing imports. when suddenly everything started to slow down, and after that the whole application flew out.

### What's the expected behavior?

It was expected that the application would quickly analyze the code and syntax color, but the syntax loaded very quickly and the application crashed.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : LGE
Device : LM-G710N

Stacktrace:
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:63)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dall-studioficial** [comment]
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-G9650

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.closeAll(Unknown Source:43)
	at com.itsaky.androidide.activities.editor.BaseEditorActivity.onDestroy(Unknown Source:75)
	at android.app.Activity.performDestroy(Activity.java:8225)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5441)
 Caused by: java.lang.RuntimeException: Unable to destroy activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5456)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5493)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by itsaky** [comment]
@dall-studioficial Do not post irrelevant content, you'll be banned from the GitHub org.
