### ISSUE TITLE
[bug] : L'application crash après être resté un peu longtemps en arrière plan 

### ISSUE THREAD

**Issue by D-P-L-U-S** [AndroidIDEOfficial/AndroidIDE#1556]
### What happened?

L'appli crash après être resté un petit moment en arrière plan.

### What's the expected behavior?

Elle devrait simplement doit redemander sur mon projet ou revenir à l'état dans lequel je l'ai laissé avant de la quitter 

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2101K7BI

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onPause(Unknown Source:11)
	at android.app.Activity.performPause(Activity.java:8726)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1638)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5296)
 Caused by: java.lang.RuntimeException: Unable to pause activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5306)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5257)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5979)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5900)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Duplicate of #1498.
