### ISSUE TITLE
[Bug]: Language selection failed

### ISSUE THREAD

**Issue by binx6** [AndroidIDEOfficial/AndroidIDE#1597]
### What happened?

Version : v2.7.0-beta (27001)
CI Build : true
Branch : main
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : RedmiK20Pro
![IMG_20240101_234021.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/123862842/38864b60-105f-4839-8193-0d5a4c1f428a)

**AndroidIDE crashed when I turned on the language option. This is a Bug. I hope it can be fixed in the next version.**

### What's the expected behavior?

Bad experience

### What version of AndroidIDE you're using?

v2.7.0-beta (27001)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : true
Branch : main
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : RedmiK20Pro

Stacktrace:
java.lang.IllegalArgumentException: Entries must have exactly one item checked, however, 0 were checked
	at com.itsaky.androidide.preferences.SingleChoicePreference.onConfigureDialogChoices(Unknown Source:78)
	at com.itsaky.androidide.preferences.ChoiceBasedDialogPreference.onConfigureDialog(Unknown Source:26)
	at com.itsaky.androidide.preferences.DialogPreference.onPreferenceClick(Unknown Source:38)
	at org.apache.commons.io.FileUtils$$ExternalSyntheticLambda0.onPreferenceClick(Unknown Source:23)
	at androidx.preference.Preference.performClick(Unknown Source:19)
	at androidx.preference.Preference$1.onClick(Unknown Source:260)
	at android.view.View.performClick(View.java:7509)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28710)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by binx6** [comment]
@itsaky

**Comment by binx6** [comment]
**Check whether the parameters meet the method requirements: First, you need to make sure that the method you are calling has any requirements for parameters. Review the documentation or source code for the method and make sure that the parameter types, ranges, lengths, etc. you provide meet the specified requirements.**

**Check parameter values: If you are sure that the type and range of the parameter are correct, then it is likely that the specific value of the parameter caused the exception. Check whether the parameter value is outside the allowed range or meets other constraints.**

**Check if the passed object is null: Some methods do not allow null objects as arguments, otherwise they throw IllegalArgumentException. Ensure that the parameter object is not null and meets the requirements of the method.**
