### ISSUE TITLE
[Bug]:  The program freezes in heavy code

### ISSUE THREAD

**Issue by appt2** [AndroidIDEOfficial/AndroidIDE#1600]
### What happened?

.

### What's the expected behavior?

AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : true
Branch : main
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 22111317PG

Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 2379416 free bytes and 2323KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.google.android.material.shape.ShapeAppearanceModel.builder(SourceFile:21)
	at com.google.android.material.shape.ShapeAppearanceModel.builder(SourceFile:6)
	at com.google.android.material.shape.ShapeAppearanceModel.builder(SourceFile:1)
	at com.google.android.material.button.MaterialButton.<init>(SourceFile:14)
	at com.google.android.material.button.MaterialButton.<init>(SourceFile:1)
 Caused by: java.lang.reflect.InvocationTargetException
 Caused by: android.view.InflateException: Binary XML file line #35 in com.itsaky.androidide:layout/layout_popup_menu_item: Error inflating class <unknown>
 Caused by: android.view.InflateException: Binary XML file line #35 in com.itsaky.androidide:layout/layout_popup_menu_item: Binary XML file line #35 in com.itsaky.androidide:layout/layout_popup_menu_item: Error inflating class <unknown>
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:883)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1035)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:688)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu$ActionsListAdapter.onCreateViewHolder(Unknown Source:19)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Unknown Source:915)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(Unknown Source:62)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:48)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:749)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:73)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:63)
	at android.view.View.measure(View.java:26640)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.measureActionsList(Unknown Source:37)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.show(Unknown Source:193)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.displayWindow(Unknown Source:168)
	at androidx.lifecycle.LiveData$1.run(Unknown Source:169)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

    

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by appt2** [comment]
https://github.com/AndroidIDEOfficial/AndroidIDE/assets/143449333/750bc432-7e13-4232-907f-624ad8de62d0

@itsaky Please fix this bug, I can't code, my client's project will be lost

**Comment by itsaky** [comment]
Closing in favor of #1694
