### ISSUE TITLE
[Bug]:  activity crashed

### ISSUE THREAD

**Issue by Tanzin01** [AndroidIDEOfficial/AndroidIDE#1604]
### What happened?

I went to test app, changed theme, came back. Now androidide started initilize project(likewhen you enter the first time except my opened files. We're opened). And a bit later , that error appeared and was told to file issue here

### What's the expected behavior?

No crash

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : true
Branch : main
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A145F

Stacktrace:
java.lang.IllegalStateException: Activity has been destroyed
	at com.itsaky.androidide.activities.editor.BaseEditorActivity.getBinding(Unknown Source:13)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorAtIndex(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getCurrentEditor(Unknown Source:47)
	at androidx.appcompat.widget.Toolbar$3.analyzeCurrentFile(Unknown Source:4)
	at androidx.appcompat.widget.Toolbar$3.onBuildSuccessful(Unknown Source:27)
	at com.itsaky.androidide.services.builder.GradleBuildService$wrap$1$onBuildFailed$1.invoke(Unknown Source:16)
	at com.itsaky.androidide.tasks.TaskExecutorKt$$ExternalSyntheticLambda1.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in 97c760a.
