### ISSUE TITLE
[Bug]: Crash when closing project

### ISSUE THREAD

**Issue by Icarus-Xu** [AndroidIDEOfficial/AndroidIDE#1621]
### What happened?

I swiped from screen edge to trigger "back" action, and the app crashed

### What's the expected behavior?

app exit to start page

### What version of AndroidIDE you're using?

v2.7.0-beta (27002)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.7.0-beta (27002)
CI Build : false
Branch : HEAD
Commit : 4f4bde4d2
Variant : arm64-v8a (release)
Build type : UNOFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.0-beta
F-Droid Version code : 27002
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : POCOF2Pro

Stacktrace:
android.system.ErrnoException: fstat failed: ENOENT (No such file or directory)
 at libcore.io.Linux.fstat(Native Method)
 at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
 at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:195)
 at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
 at libcore.io.IoBridge.open(IoBridge.java:563)
 Caused by: java.io.FileNotFoundException: /storage/emulated/0/AndroidIDEProjects/My Application/.androidide/editor/openedFiles.json: fstat failed: ENOENT (No such file or directory)
 at libcore.io.IoBridge.open(IoBridge.java:574)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
 at kotlinx.coroutines.AwaitKt.writeText$default(Unknown Source:23)
 at com.itsaky.androidide.viewmodel.EditorViewModel$writeOpenedFiles$1.invokeSuspend(Unknown Source:43)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
 at androidx.work.Worker$2.run(Unknown Source:39)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
```

### Duplicate issues

- [X] This issue has not been reported yet.

I found issue #1478 has similar crash stack but minor differences, not sure if it's duplicate, plz kindly check.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> I found issue https://github.com/AndroidIDEOfficial/AndroidIDE/issues/1478 has similar crash stack but minor differences, not sure if it's duplicate, plz kindly check.

I don't think this is a duplicate. I'll look into the issue ASAP.

**Comment by Icarus-Xu** [comment]
Thank you
