### ISSUE TITLE
[Bug]: Crashed while compilation

### ISSUE THREAD

**Issue by manjeet123567** [AndroidIDEOfficial/AndroidIDE#1627]
### What happened?

AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : true
Branch : main
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : I2217

Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1651760 free bytes and 1613KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.util.Formatter$Flags.parse(Formatter.java:4718)
	at java.util.Formatter$FormatSpecifier.flags(Formatter.java:2896)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2961)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2778)
	at java.util.Formatter.parse(Formatter.java:2711)
	at java.util.Formatter.format(Formatter.java:2660)
	at java.util.Formatter.format(Formatter.java:2614)
	at java.lang.String.format(String.java:4017)
	at com.vivo.vspa.promotion.PromotionManager.onVSync(PromotionManager.java:191)
	at android.view.VivoChoreographerImpl.onVSync(VivoChoreographerImpl.java:27)
	at android.view.Choreographer$FrameDisplayEventReceiver.onVsync(Choreographer.java:1694)
	at android.view.DisplayEventReceiver.dispatchVsync(DisplayEventReceiver.java:350)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:176)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9164)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

    

### What's the expected behavior?

Crashing 

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Closing in favor of #1694
