### ISSUE TITLE
[Bug]: Newer version still hates comma in parenthesis of method call Java

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1628]
### What happened?

Told in Title

### What's the expected behavior?

Well maybe trycatch might escape the crash.(using 2.7.0 but it is not option to pick in list  below so i picked previous version)

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : armeabi-v7a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A202F

Stacktrace:
com.itsaky.androidide.progress.ProcessCancelledException
	at com.itsaky.androidide.progress.ICancelChecker$Default.abortIfCancelled(Unknown Source:9)
	at com.itsaky.androidide.tasks.JobCancelChecker.abortIfCancelled(Unknown Source:5)
	at com.itsaky.androidide.lsp.java.providers.CancelableServiceProvider.abortIfCancelled(Unknown Source:2)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(Unknown Source:40)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$2.invokeSuspend(Unknown Source:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pavel5750cz** [comment]
User way to prevent this crash is type comma and then quickly save.

**Comment by itsaky** [comment]
From the crash report, it seems you're using v2.6.1-beta. Please upgrade to the latest version.
