### ISSUE TITLE
AndroidIDE Crash Report

### ISSUE THREAD

**Issue by kiepon1234** [AndroidIDEOfficial/AndroidIDE#1666]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : TECNO
Device : TECNOLH7n

Stacktrace:
java.lang.IllegalStateException: No TreeSitterLanguage found for type log
	at androidx.navigation.NavController$handleDeepLink$2.invoke(SourceFile:21)
	at androidx.navigation.NavController$handleDeepLink$2.invoke(SourceFile:248)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readSchemeAsync$1.invokeSuspend(Unknown Source:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(Unknown Source:138)
	at com.sun.jna.VarArgsChecker$1.startCoroutineCancellable$default(Unknown Source:13)
	at kotlinx.coroutines.AbstractCoroutine.start(Unknown Source:81)
	at kotlin.ResultKt.launch(Unknown Source:23)
	at kotlin.ResultKt.launch$default(Unknown Source:14)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider.readSchemeAsync$default(Unknown Source:84)
	at com.itsaky.androidide.fragments.output.LogViewFragment.onViewCreated(Unknown Source:89)
	at com.itsaky.androidide.fragments.output.AppLogFragment.onViewCreated(Unknown Source:5)
	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:255)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:148)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:1070)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:81)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(Unknown Source:31)
	at androidx.fragment.app.BackStackRecord.commitNow(Unknown Source:9)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(Unknown Source:181)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(Unknown Source:2)
	at androidx.recyclerview.widget.ChildHelper.addView(Unknown Source:40)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(Unknown Source:219)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:33)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:48)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:818)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:73)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:71)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:7)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:60)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(Unknown Source:391)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(Unknown Source:203)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:40)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:57)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:822)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6520)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4188)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3573)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2519)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9516)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1326)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1334)
	at android.view.Choreographer.doCallbacks(Choreographer.java:967)
	at android.view.Choreographer.doFrame(Choreographer.java:881)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1309)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:204)
	at android.os.Looper.loop(Looper.java:291)
	at android.app.ActivityThread.main(ActivityThread.java:8129)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

    

### Expected behavior

dont know

### Version name

2.7.0-beta

### Download source

GitHub

**Comment by taxi100** [comment]
AndroidIDE Crash Report
Version : v2.7.0-beta (27002)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : armeabi-v7a (release)
Build type : OFFICIAL
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2004J19C

Stacktrace:
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:151)
	at android.app.Dialog.<init>(Dialog.java:199)
	at androidx.activity.ComponentDialog.<init>(Unknown Source:5)
	at androidx.appcompat.app.AppCompatDialog.<init>(Unknown Source:22)
	at androidx.appcompat.app.AlertDialog.<init>(Unknown Source:4)
	at org.commonmark.internal.BlockContent.create(Unknown Source:10)
	at com.google.android.material.dialog.MaterialAlertDialogBuilder.create(Unknown Source:0)
	at org.commonmark.internal.BlockContent.show(Unknown Source:0)
	at androidx.room.SharedSQLiteStatement$stmt$2.invoke(SourceFile:69)
	at com.itsaky.androidide.fragments.MainFragment$doClone$cloneJob$1.invokeSuspend(Unknown Source:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at org.greenrobot.eventbus.AsyncPoster.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

**Comment by taxi100** [comment]
AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2004J19C

Stacktrace:
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:151)
	at android.app.Dialog.<init>(Dialog.java:199)
	at androidx.activity.ComponentDialog.<init>(Unknown Source:5)
	at androidx.appcompat.app.AppCompatDialog.<init>(Unknown Source:22)
	at androidx.appcompat.app.AlertDialog.<init>(Unknown Source:4)
	at org.commonmark.internal.BlockContent.create(Unknown Source:10)
	at com.google.android.material.dialog.MaterialAlertDialogBuilder.create(Unknown Source:0)
	at org.commonmark.internal.BlockContent.show(Unknown Source:0)
	at androidx.room.SharedSQLiteStatement$stmt$2.invoke(SourceFile:69)
	at com.itsaky.androidide.fragments.MainFragment$doClone$cloneJob$1.invokeSuspend(Unknown Source:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at org.greenrobot.eventbus.AsyncPoster.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

**Comment by taxi100** [comment]
AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2004J19C

Stacktrace:
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:151)
	at android.app.Dialog.<init>(Dialog.java:199)
	at androidx.activity.ComponentDialog.<init>(Unknown Source:5)
	at androidx.appcompat.app.AppCompatDialog.<init>(Unknown Source:22)
	at androidx.appcompat.app.AlertDialog.<init>(Unknown Source:4)
	at org.commonmark.internal.BlockContent.create(Unknown Source:10)
	at com.google.android.material.dialog.MaterialAlertDialogBuilder.create(Unknown Source:0)
	at org.commonmark.internal.BlockContent.show(Unknown Source:0)
	at androidx.room.SharedSQLiteStatement$stmt$2.invoke(SourceFile:69)
	at com.itsaky.androidide.fragments.MainFragment$doClone$cloneJob$1.invokeSuspend(Unknown Source:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at org.greenrobot.eventbus.AsyncPoster.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

**Comment by ghost** [comment]
AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : realme
Device : RMX3371

Stacktrace:
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-2,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:143)
	at android.app.Dialog.<init>(Dialog.java:197)
	at androidx.activity.ComponentDialog.<init>(Unknown Source:5)
	at androidx.appcompat.app.AppCompatDialog.<init>(Unknown Source:22)
	at androidx.appcompat.app.AlertDialog.<init>(Unknown Source:4)
	at org.commonmark.internal.BlockContent.create(Unknown Source:10)
	at com.google.android.material.dialog.MaterialAlertDialogBuilder.create(Unknown Source:0)
	at org.commonmark.internal.BlockContent.show(Unknown Source:0)
	at androidx.room.SharedSQLiteStatement$stmt$2.invoke(SourceFile:69)
	at com.itsaky.androidide.fragments.MainFragment$doClone$cloneJob$1.invokeSuspend(Unknown Source:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at org.greenrobot.eventbus.AsyncPoster.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

**Comment by bocajthomas** [comment]
AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-S918B

Stacktrace:
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-2,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:168)
	at android.app.Dialog.<init>(Dialog.java:279)
	at androidx.activity.ComponentDialog.<init>(Unknown Source:5)
	at androidx.appcompat.app.AppCompatDialog.<init>(Unknown Source:22)
	at androidx.appcompat.app.AlertDialog.<init>(Unknown Source:4)
	at org.commonmark.internal.BlockContent.create(Unknown Source:10)
	at com.google.android.material.dialog.MaterialAlertDialogBuilder.create(Unknown Source:0)
	at org.commonmark.internal.BlockContent.show(Unknown Source:0)
	at androidx.room.SharedSQLiteStatement$stmt$2.invoke(SourceFile:69)
	at com.itsaky.androidide.fragments.MainFragment$doClone$cloneJob$1.invokeSuspend(Unknown Source:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at org.greenrobot.eventbus.AsyncPoster.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
