### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hmze123** [AndroidIDEOfficial/AndroidIDE#1669]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 21081111RG

Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 747328 free bytes and 729KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.itsaky.androidide.treesitter.DefaultObjectFactory.createNode(Unknown Source:0)
	at com.itsaky.androidide.treesitter.internal.NativeObjectFactory.createNode(Unknown Source:10)
	at com.itsaky.androidide.treesitter.internal.NativeObjectFactory.createQueryCapture(Unknown Source:0)
	at com.itsaky.androidide.treesitter.TSQueryCursor$Native.nextMatch(Native Method)
	at com.itsaky.androidide.treesitter.TSQueryCursor.nextMatch(Unknown Source:12)
	at io.github.rosemoe.sora.editor.ts.LineSpansGenerator.captureRegion(Unknown Source:415)
	at io.github.rosemoe.sora.editor.ts.LineSpansGenerator$read$1.getSpansOnLine(Unknown Source:162)
	at io.github.rosemoe.sora.widget.CodeEditor.getSpansForLine(Unknown Source:34)
	at io.github.rosemoe.sora.widget.EditorRenderer.buildMeasureCacheForLines(Unknown Source:178)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(Unknown Source:246)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(Unknown Source:33)
	at android.view.View.draw(View.java:23481)
	at android.view.View.updateDisplayListIfDirty(View.java:22299)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22239)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4992)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4681)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3868)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2577)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9638)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

    

### Expected behavior

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 21081111RG

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 21081111RG

### Download source

GitHub

### Relevant log output

```bash
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 21081111RG
```

**Comment by itsaky** [comment]
Closing in favor of #1694
