### ISSUE TITLE
Android ide crashed while going back to the ide after a successful launch app 

### ISSUE THREAD

**Issue by AIM-less** [AndroidIDEOfficial/AndroidIDE#1717]
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : realme
Device : RMX3511

Stacktrace:
java.lang.IllegalStateException: Activity has been destroyed
	at com.itsaky.androidide.activities.editor.BaseEditorActivity.getBinding(Unknown Source:13)
	at com.blankj.utilcode.util.KeyboardUtils$2.onGlobalLayout(Unknown Source:25)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3284)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2213)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8842)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1392)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:919)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1377)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1004)

**Comment by AIM-less** [comment]
Thanks
