### ISSUE TITLE
[Question]: Couldn't run tasks

### ISSUE THREAD

**Issue by binx6** [AndroidIDEOfficial/AndroidIDE#1737]
I attempted to use `AndroidIDE` to build the latest Gradle [8.7-rc-1](https://github.com/gradle/gradle/releases/tag/v8.7.0-RC1) with Gradle plugin [8.4.0-alpha10](https://mvnrepository.com/artifact/com.android.application/com.android.application.gradle.plugin) version, although the build succeeded, but can't run tasks, it seems that there is no support to it? I also saw a similar issue #1681 (though the similarity is not much).
![IMG_20240223_132608.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/123862842/b2dcb2f8-322e-4570-90e5-4a03de253fc1)

**Comment by binx6** [comment]
**I hope the next version can support it as soon as possible.**

**Comment by itsaky** [comment]
Android Gradle Plugin v8.4.x is not supported yet.

<details>
<summary>Relevant logs for reference</summary>

```
ToolingApiErrorStream     E   SEVERE: Internal error: org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: AndroidProject.getModelSyncFiles(). 
ToolingApiErrorStream     E   The version of Gradle you connect to does not support that method. 
ToolingApiErrorStream     E   To resolve the problem you can change/upgrade the target version of Gradle you connect to. 
ToolingApiErrorStream     E   Alternatively, you can ignore this exception and read other information from the model. 
ToolingApiErrorStream     E   java.util.concurrent.CompletionException: org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: AndroidProject.getModelSyncFiles(). 
ToolingApiErrorStream     E   The version of Gradle you connect to does not support that method. 
ToolingApiErrorStream     E   To resolve the problem you can change/upgrade the target version of Gradle you connect to. 
ToolingApiErrorStream     E   Alternatively, you can ignore this exception and read other information from the model. 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) 
ToolingApiErrorStream     E   Caused by: org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: AndroidProject.getModelSyncFiles(). 
ToolingApiErrorStream     E   The version of Gradle you connect to does not support that method. 
ToolingApiErrorStream     E   To resolve the problem you can change/upgrade the target version of Gradle you connect to. 
ToolingApiErrorStream     E   Alternatively, you can ignore this exception and read other information from the model. 
ToolingApiErrorStream     E   	at org.gradle.tooling.model.internal.Exceptions.unsupportedMethod(Exceptions.java:33) 
ToolingApiErrorStream     E   	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:468) 
ToolingApiErrorStream     E   	at jdk.proxy2/jdk.proxy2.$Proxy32.getModelSyncFiles(Unknown Source) 
ToolingApiErrorStream     E   	at com.itsaky.androidide.tooling.impl.internal.AndroidProjectImpl.getModelSyncFiles$lambda$9(AndroidProjectImpl.kt:155) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) 
ToolingApiErrorStream     E   	... 6 more 
ToolingApiErrorStream     E    
```

</details>

**Comment by binx6** [comment]
Currently, I've go back to the Gradle plugin v8.2.0 and it works fine. I'll use it for the time being.

**Comment by itsaky** [comment]
Commit d5762bddb84996aa1f8929de253004e8a26b516b adds support for AGP 8.3.0. Support for AGP 8.4.0 will be added when it is stable.

**Comment by binx6** [comment]
Good job.
