### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by JmrGamers** [AndroidIDEOfficial/AndroidIDE#1759]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c78
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : I2018

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.lsp.java.JavaLanguageServer
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.show(Unknown Source:136)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.displayWindow(Unknown Source:168)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu$$ExternalSyntheticLambda1.run(Unknown Source:17)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8463)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)

    

### Expected behavior

_

### Version name

_

### Download source

GitHub

### Relevant log output

```bash
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c78
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : I2018

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.lsp.java.JavaLanguageServer
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.show(Unknown Source:136)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.displayWindow(Unknown Source:168)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu$$ExternalSyntheticLambda1.run(Unknown Source:17)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8463)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)
```

**Comment by itsaky** [comment]
Update AndroidIDE to the latest version.

**Comment by JmrGamers** [comment]
> Update AndroidIDE to the latest version.

Updated last night but still crashing.
