### ISSUE TITLE
Could not find com.itsaky.androidide:gradle-plugin:2.7.1-beta-18124288a-SNAPSHOT

### ISSUE THREAD

**Issue by BinTianqi** [AndroidIDEOfficial/AndroidIDE#1760]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I created a _Empty project_ in androidide, then gradle sync failed. 
I tried to re-install the app then install android-sdk and jdk17 automatically, but this issue still exist.

### Expected behavior

Build success

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : 1758/merge
Commit : 18124288a
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OnePlus
Device : GM1901

### Download source

GitHub

### Relevant log output

**Build output**
```bash
Starting build...

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration 'classpath'.
> Could not find com.itsaky.androidide:gradle-plugin:2.7.1-beta-dca187da6-SNAPSHOT.
  Searched in the following locations:
    - https://s01.oss.sonatype.org/content/repositories/snapshots/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
    - https://s01.oss.sonatype.org/content/repositories/snapshots/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
    - https://s01.oss.sonatype.org/content/groups/public/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
    - https://s01.oss.sonatype.org/content/groups/public/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
    - https://repo.maven.apache.org/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
    - https://repo.maven.apache.org/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
    - https://dl.google.com/dl/android/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
    - https://dl.google.com/dl/android/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
  Required by:
      unspecified:unspecified:unspecified

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 19s

```

**IDE Logs**

```bash
EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
EditorActivity            D   No variant selection information available. Default build variants will be selected. 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
ToolingApiServer          D   ToolingApiMain             Running on Java version:  17-internal  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectParams(directory=/storage/emulated/0/AndroidIDEProjects/My Application, gradleDistribution=GradleDistributionParams(type=GRADLE_WRAPPER, value=), androidParams=AndroidInitializationParams(variantSelections={}))  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiErrorStream     E   SLF4J(W): No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J(W): Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 53ms  
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: true 
ToolingApiServer          D   StopWatch                  Project connection established in 22ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, -Pandroidide.logsender.isEnabled=true]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
EditorActivity            D   [onPause]  No opened files.  Opened files cache reset to null. 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
ToolingApiServer          E   ToolingApiServerImpl       Failed to initialize project 
ToolingApiServer          E  org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.itsaky.androidide:gradle-plugin:2.7.1-beta-dca187da6-SNAPSHOT.
ToolingApiServer          E  Searched in the following locations:
ToolingApiServer          E    - https://s01.oss.sonatype.org/content/repositories/snapshots/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
ToolingApiServer          E    - https://s01.oss.sonatype.org/content/repositories/snapshots/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
ToolingApiServer          E    - https://s01.oss.sonatype.org/content/groups/public/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
ToolingApiServer          E    - https://s01.oss.sonatype.org/content/groups/public/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
ToolingApiServer          E    - https://repo.maven.apache.org/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
ToolingApiServer          E    - https://repo.maven.apache.org/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
ToolingApiServer          E    - https://dl.google.com/dl/android/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/maven-metadata.xml
ToolingApiServer          E    - https://dl.google.com/dl/android/maven2/com/itsaky/androidide/gradle-plugin/2.7.1-beta-dca187da6-SNAPSHOT/gradle-plugin-2.7.1-beta-dca187da6-SNAPSHOT.pom
ToolingApiServer          E  Required by:
ToolingApiServer          E      unspecified:unspecified:unspecified
ToolingApiServer          E   Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration 'classpath'.
ToolingApiServer          E  	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.mapFailure(DefaultConfiguration.java:1716)
ToolingApiServer          E  	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$3400(DefaultConfiguration.java:177)
ToolingApiServer          E  	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$DefaultResolutionHost.mapFailure(DefaultConfiguration.java:2443)
ToolingApiServer          E  	at org.gradle.api.internal.artifacts.configurations.ResolutionHost.rethrowFailure(ResolutionHost.java:30)
ToolingApiServer          E  	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:74)
ToolingApiServer          E  	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:130)
ToolingApiServer          E  	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:171)
ToolingApiServer          E  	at org.gradle.internal.classpath.DefaultClassPath.of(DefaultClassPath.java:56)
ToolingApiServer          E  	at org.gradle.api.internal.initialization.DefaultScriptClassPathResolver.resolveClassPath(DefaultScriptClassPathResolver.java:86)
ToolingApiServer          E  	at org.gradle.api.internal.initialization.DefaultScriptHandler.getInstrumentedScriptClassPath(DefaultScriptHandler.java:93)
ToolingApiServer          E  	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.defineScriptHandlerClassScope(DefaultPluginRequestApplicator.java:176)
ToolingApiServer          E  	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:90)
ToolingApiServer          E  	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:117)
ToolingApiServer          E  	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
ToolingApiServer          E  	at org.gradle.configuration.BuildOperationScriptPlugin.lambda$apply$0(BuildOperationScriptPlugin.java:62)
ToolingApiServer          E  	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
ToolingApiServer          E  	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:62)
ToolingApiServer          E  	at org.gradle.configuration.DefaultInitScriptProcessor.process(DefaultInitScriptProcessor.java:50)
ToolingApiServer          E  	at org.gradle.initialization.InitScriptHandler$1.run(InitScriptHandler.java:56)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
ToolingApiServer          E  	at org.gradle.initialization.InitScriptHandler.executeScripts(InitScriptHandler.java:51)
ToolingApiServer          E  	at org.gradle.initialization.InitScriptHandlingSettingsLoader.findAndLoadSettings(InitScriptHandlingSettingsLoader.java:32)
ToolingApiServer          E  	at org.gradle.api.internal.initialization.CacheConfigurationsHandlingSettingsLoader.findAndLoadSettings(CacheConfigurationsHandlingSettingsLoader.java:36)
ToolingApiServer          E  	at org.gradle.initialization.GradlePropertiesHandlingSettingsLoader.findAndLoadSettings(GradlePropertiesHandlingSettingsLoader.java:38)
ToolingApiServer          E  	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:31)
ToolingApiServer          E  	at org.gradle.initialization.BuildOperationFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperationFiringSettingsPreparer.java:71)
ToolingApiServer          E  	at org.gradle.initialization.BuildOperationFiringSettingsPreparer$LoadBuild.run(BuildOperationFiringSettingsPreparer.java:66)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
ToolingApiServer          E  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
ToolingApiServer          E  	at org.gradle.initialization.BuildOperationFiringSettingsPreparer.prepareSettings(BuildOperationFiringSettingsPreparer.java:54)
ToolingApiServer          E  	at org.gradle.initialization.VintageBuildModelController.lambda$prepareSettings$1(VintageBuildModelController.java:80)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.lambda$doTransition$14(StateTransitionController.java:255)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:254)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.lambda$transitionIfNotPreviously$11(StateTransitionController.java:213)
ToolingApiServer          E  	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:34)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.transitionIfNotPreviously(StateTransitionController.java:209)
ToolingApiServer          E  	at org.gradle.initialization.VintageBuildModelController.prepareSettings(VintageBuildModelController.java:80)
ToolingApiServer          E  	at org.gradle.initialization.VintageBuildModelController.getConfiguredModel(VintageBuildModelController.java:63)
ToolingApiServer          E  	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$withProjectsConfigured$1(DefaultBuildLifecycleController.java:122)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.lambda$notInState$3(StateTransitionController.java:132)
ToolingApiServer          E  	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.notInState(StateTransitionController.java:128)
ToolingApiServer          E  	at org.gradle.internal.build.DefaultBuildLifecycleController.withProjectsConfigured(DefaultBuildLifecycleController.java:122)
ToolingApiServer          E  	at org.gradle.internal.build.DefaultBuildToolingModelController.locateBuilderForTarget(DefaultBuildToolingModelController.java:57)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeModelCreator$DefaultBuildTreeModelController.lambda$locateBuilderForTarget$0(DefaultBuildTreeModelCreator.java:73)
ToolingApiServer          E  	at org.gradle.internal.build.DefaultBuildLifecycleController.withToolingModels(DefaultBuildLifecycleController.java:215)
ToolingApiServer          E  	at org.gradle.internal.build.AbstractBuildState.withToolingModels(AbstractBuildState.java:140)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeModelCreator$DefaultBuildTreeModelController.locateBuilderForTarget(DefaultBuildTreeModelCreator.java:73)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeModelCreator$DefaultBuildTreeModelController.locateBuilderForDefaultTarget(DefaultBuildTreeModelCreator.java:68)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.runner.DefaultBuildController.getTarget(DefaultBuildController.java:157)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.runner.DefaultBuildController.getModel(DefaultBuildController.java:101)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ParameterAwareBuildControllerAdapter.getModel(ParameterAwareBuildControllerAdapter.java:40)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:116)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.getModel(NestedActionAwareBuildControllerAdapter.java:32)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:79)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.getModel(NestedActionAwareBuildControllerAdapter.java:32)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:64)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.getModel(NestedActionAwareBuildControllerAdapter.java:32)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.sync.AbstractModelBuilder$Companion$getModelAndLog$1.invoke(AbstractModelBuilder.kt:118)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.sync.AbstractModelBuilder$Companion.withStopWatch(AbstractModelBuilder.kt:181)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.sync.AbstractModelBuilder$Companion.getModelAndLog(AbstractModelBuilder.kt:116)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.sync.AbstractModelBuilder.getModelAndLog(AbstractModelBuilder.kt)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.sync.RootModelBuilder.build$lambda$3(RootModelBuilder.kt:53)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:65)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.runAction(AbstractClientProvidedBuildActionRunner.java:131)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:104)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:84)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeModelCreator.fromBuildModel(DefaultBuildTreeModelCreator.java:57)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$fromBuildModel$2(DefaultBuildTreeLifecycleController.java:81)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$4(DefaultBuildTreeLifecycleController.java:98)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:169)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.lambda$transition$7(StateTransitionController.java:169)
ToolingApiServer          E  	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
ToolingApiServer          E  	at org.gradle.internal.model.StateTransitionController.transition(StateTransitionController.java:169)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.runBuild(DefaultBuildTreeLifecycleController.java:95)
ToolingApiServer          E  	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.fromBuildModel(DefaultBuildTreeLifecycleController.java:73)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner.runClientAction(AbstractClientProvidedBuildActionRunner.java:43)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:48)
ToolingApiServer          E  	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
ToolingApiServer          E  	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:49)
ToolingApiServer          E  	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run
```

**Comment by ThatMG393** [comment]
use builds from branch dev

https://github.com/AndroidIDEOfficial/AndroidIDE/actions/workflows/build.yml?query=branch%3Adev

**Comment by BinTianqi** [comment]
gradle sync success
thanks

**Comment by yykkxx** [comment]
i have the same question，but i use the latest apk
