### ISSUE TITLE
what happen

### ISSUE THREAD

**Issue by 2376780283** [AndroidIDEOfficial/AndroidIDE#1766]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 28
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : HUAWEI
Device : PAR-AL00

Stacktrace:
java.util.zip.ZipException: No entries
	at java.util.zip.ZipFile.<init>(ZipFile.java:252)
	at java.util.zip.ZipFile.<init>(ZipFile.java:152)
	at java.util.jar.JarFile.<init>(JarFile.java:160)
	at java.util.jar.JarFile.<init>(JarFile.java:124)
	at openjdk.tools.javac.file.FSInfo.getJarClassPath(Unknown Source:6)
	at openjdk.tools.javac.file.CacheFSInfo.getJarClassPath(Unknown Source:13)
	at com.itsaky.androidide.projects.ProjectManagerImpl$setupProject$4$jobs$1$1.invokeSuspend(Unknown Source:143)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

### Expected behavior

i don t know

### Version name

2.7.1 beta

### Download source

GitHub

**Comment by itsaky** [comment]
Dupliate of #1708.
