### ISSUE TITLE
Trying create game with libGDX, but catch error

### ISSUE THREAD

**Issue by BGFlamer4ik** [AndroidIDEOfficial/AndroidIDE#1780]
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 2209116AG

Stacktrace:
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(Unknown Source:2264)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(Unknown Source:33)
	at android.view.View.draw(View.java:23845)
	at android.view.View.updateDisplayListIfDirty(View.java:22682)
	at android.view.View.draw(View.java:23559)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4344)
	at android.view.View.updateDisplayListIfDirty(View.java:22671)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4570)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4543)
	at android.view.View.updateDisplayListIfDirty(View.java:22619)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:693)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5198)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4899)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2725)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9812)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1505)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1513)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1128)
	at android.view.Choreographer.doFrame(Choreographer.java:1042)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1481)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by itsaky** [comment]
Use the bug report template to report bugs. Also, we'll need more context about the issue.
