### ISSUE TITLE
Crash after build

### ISSUE THREAD

**Issue by Twinnon** [AndroidIDEOfficial/AndroidIDE#1792]
AndroidIDE Crash Report
Version : v2.7.1-beta (27101)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : armeabi-v7a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 29
Supported ABIs : [armeabi-v7a, armeabi]
Manufacturer : INFINIX MOBILITY LIMITED
Device : InfinixX657

Stacktrace:
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:966)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1577)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1343)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1309)
	at io.github.rosemoe.sora.widget.base.EditorPopupWindow.applyWindowAttributes(Unknown Source:152)
	at com.itsaky.androidide.editor.ui.AbstractPopupWindow.show(Unknown Source:25)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.show(Unknown Source:224)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.displayWindow(Unknown Source:168)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu$$ExternalSyntheticLambda1.run(Unknown Source:21)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7605)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by itsaky** [comment]
Fixed in 940c7b0aa22bc5ee47e8263015089003d1f72b8d.
