### ISSUE TITLE
problem Cannot run application. No application modules found in project.

### ISSUE THREAD

**Issue by AnasAbdullh** [AndroidIDEOfficial/AndroidIDE#1842]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

When I run any project on GitHub, a message appears "Cannot run application. No application modules found in project."

What is the solution ?
![Screenshot_2024-07-13-03-20-04-01_9ad8e654efd333b66ab21513aa36e36c](https://github.com/user-attachments/assets/2c25730f-a9f9-4826-abf9-b1d9ccdd9676)

### Expected behavior

I expected the app to work 

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OnePlus
Device : NE2217

### Download source

GitHub

### Relevant log output

```bash
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
2024-07-13T15:16:21.708+0000 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] CONFIGURE FAILED in 208ms
2024-07-13T15:16:21.709+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Build finished for file system watching' started
2024-07-13T15:16:21.709+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Build finished for file system watching'
2024-07-13T15:16:21.709+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Build finished for file system watching' completed
2024-07-13T15:16:21.712+0000 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-supplier (/data/data/com.itsaky.androidide/files/home/.gradle/caches/8.4/md-supplier)
2024-07-13T15:16:21.712+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-supplier (/data/data/com.itsaky.androidide/files/home/.gradle/caches/8.4/md-supplier).
2024-07-13T15:16:21.713+0000 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-rule (/data/data/com.itsaky.androidide/files/home/.gradle/caches/8.4/md-rule)
2024-07-13T15:16:21.713+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-rule (/data/data/com.itsaky.androidide/files/home/.gradle/caches/8.4/md-rule).
2024-07-13T15:16:21.714+0000 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
2024-07-13T15:16:21.714+0000 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
2024-07-13T15:16:21.714+0000 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.0 secs
2024-07-13T15:16:21.715+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Run build'
2024-07-13T15:16:21.715+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Run build' completed
2024-07-13T15:16:21.715+0000 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker: released lock on worker lease
2024-07-13T15:16:21.724+0000 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
2024-07-13T15:16:21.724+0000 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
2024-07-13T15:16:21.725+0000 [DEBUG] [org.gradle.cache.internal.DefaultPersistentDirectoryStore] VCS Checkout Cache (/storage/emulated/0/AndroidIDEProjects/WiFiList/.gradle/vcs-1) has last been fully cleaned up 0 hours ago
2024-07-13T15:16:21.725+0000 [DEBUG] [org.gradle.cache.internal.DefaultCacheCoordinator] Cache VCS Checkout Cache (/storage/emulated/0/AndroidIDEProjects/WiFiList/.gradle/vcs-1) was closed 0 times.
2024-07-13T15:16:21.725+0000 [DEBUG] [org.gradle.cache.internal.DefaultCacheCoordinator] Cache VCS metadata (/storage/emulated/0/AndroidIDEProjects/WiFiList/.gradle/8.4/vcsMetadata) was closed 0 times.
2024-07-13T15:16:21.735+0000 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for checksums cache (/storage/emulated/0/AndroidIDEProjects/WiFiList/.gradle/8.4/checksums)
2024-07-13T15:16:21.736+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on checksums cache (/storage/emulated/0/AndroidIDEProjects/WiFiList/.gradle/8.4/checksums).
2024-07-13T15:16:21.747+0000 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (/storage/emulated/0/AndroidIDEProjects/WiFiList/.gradle/8.4/fileHashes)
2024-07-13T15:16:21.747+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (/storage/emulated/0/AndroidIDEProjects/WiFiList/.gradle/8.4/fileHashes).
2024-07-13T15:16:21.757+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
```

**Comment by CyberXCoder-6649** [comment]
It's Duplicate of #1830

**Comment by AnasAbdullh** [comment]
> It's Duplicate of #1830

What is the solution ?

**Comment by CyberXCoder-6649** [comment]
> > It's Duplicate of #1830
> 
> What is the solution ?

Wait for update

**Comment by paomeng-game** [comment]
Facing this problem either... Looking forward to the solution.
![Uploading Screenshot_20240721_123516_com.itsaky.androidide.jpg…]()

**Comment by paomeng-game** [comment]
Facing this problem either... Looking forward to the solution.
![Screenshot_20240721_123516_com itsaky androidide](https://github.com/user-attachments/assets/37de348a-a1d2-4a9c-85c0-e0dcbf4a3104)
