### ISSUE TITLE
Automatically Forcestop the app if 10minutes coding or above

### ISSUE THREAD

**Issue by marvsl** [AndroidIDEOfficial/AndroidIDE#1847]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

When i code 10minutes above like that android ide gets 
![Screenshot_20240625-192511](https://github.com/user-attachments/assets/16c0718e-ed93-42f5-bd8f-c95b8e46e0b1)
forcetop

### Expected behavior

I want to fix this because it dont save the code the i putter when it focestop

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : dev
Commit : 275d98c23
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : ITEL
Device : itelS666LN

### Download source

GitHub

### Relevant log output

```bash
java.lang.IllegalStateException: Activity has been destroyed
	at com.itsaky.androidide.activities.PreferencesActivity.getBinding(Unknown Source:13)
	at com.itsaky.androidide.activities.PreferencesActivity.onApplySystemBarInsets(Unknown Source:0)
	at com.itsaky.androidide.app.EdgeToEdgeIDEActivity.applyEdgeToEdge(Unknown Source:157)
	at com.itsaky.androidide.app.EdgeToEdgeIDEActivity.onCreate(SourceFile:1)
	at com.itsaky.androidide.activities.PreferencesActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:8338)
	at android.app.Activity.performCreate(Activity.java:8317)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1388)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3766)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.activities.PreferencesActivity}: java.lang.IllegalStateException: Activity has been destroyed
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3844)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3981)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5987)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5878)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5946)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2413)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:204)
	at android.os.Looper.loop(Looper.java:291)
	at android.app.ActivityThread.main(ActivityThread.java:8155)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1136)
```

**Comment by PrashantRawatCoder** [comment]
Can you provide you device specifications?
Like android version , ram , storage , cpu etc. Because it can be due to less recourse in the phone. 

Or maybe it can be due to Android Phantom Killer.
