### ISSUE TITLE
NativeActivity Error

### ISSUE THREAD

**Issue by Mrezadwiprasetiawan** [AndroidIDEOfficial/AndroidIDE#1865]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I'm trying to build native activities here. At first I thought my code was the error, after returning it became a java activity. This error appears

### Expected behavior

Of course there's no error

### Version name

2.7.1 beta

### Download source

GitHub

### Relevant log output

```bash
--------- beginning of crash
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           FATAL EXCEPTION: main
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           Process: id.pras.testnative, PID: 13153
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           java.lang.RuntimeException: Unable to get provider com.itsaky.androidide.logsender.utils.LogSenderInstaller: java.lang.ClassNotFoundException: Didn't find class "com.itsaky.androidide.logsender.utils.LogSenderInstaller" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~_ufh8NEvjQG9hFMwevgVDQ==/id.pras.testnative-3bwNN8HPzQ9cp89g3SKPcQ==/lib/arm64, /data/app/~~_ufh8NEvjQG9hFMwevgVDQ==/id.pras.testnative-3bwNN8HPzQ9cp89g3SKPcQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.ActivityThread.installProvider(ActivityThread.java:7803)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7309)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7203)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.ActivityThread.access$1500(ActivityThread.java:269)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.os.Handler.dispatchMessage(Handler.java:106)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.os.Looper.loop(Looper.java:257)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.ActivityThread.main(ActivityThread.java:8218)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at java.lang.reflect.Method.invoke(Native Method)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.itsaky.androidide.logsender.utils.LogSenderInstaller" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~_ufh8NEvjQG9hFMwevgVDQ==/id.pras.testnative-3bwNN8HPzQ9cp89g3SKPcQ==/lib/arm64, /data/app/~~_ufh8NEvjQG9hFMwevgVDQ==/id.pras.testnative-3bwNN8HPzQ9cp89g3SKPcQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
08-01 13:24:54.361 13153 13153 E  AndroidRuntime:           	at android.app.ActivityThread.installProvider(ActivityThread.java:7787)
```

**Comment by Mrezadwiprasetiawan** [comment]
It's because I set android:hasCode="false" XD. Sorry

**Comment by CyberXCoder-6649** [comment]
Is issue solved? Then closed it.

**Comment by itsaky** [comment]
> It's because I set android:hasCode="false" XD. Sorry

Assuming the issue has been resolved.
