### ISSUE TITLE
The ide exited after project build finished

### ISSUE THREAD

**Issue by joytou** [AndroidIDEOfficial/AndroidIDE#1895]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

It turn error after the project builded.

### Expected behavior

1. Open the ide.
2. Open existing project.
3. Confirm open the project on phone.
4. Wait for the ide build auto.
5. After build finish, it turn to the "Get started".

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : HUAWEI
Device : PCT-AL10

### Download source

GitHub

### Relevant log output

```bash
java.lang.StackOverflowError: stack size 1039KB
	at com.google.gson.internal.LinkedTreeMap$KeySet$1.<init>(SourceFile:2)
	at com.google.gson.internal.LinkedTreeMap$KeySet.iterator(Unknown Source:14)
	at com.itsaky.androidide.projects.api.AndroidModule.getCompileModuleProjects(Unknown Source:42)
	at com.itsaky.androidide.projects.api.AndroidModule.getCompileModuleProjects(Unknown Source:106)
	at com.itsaky.androidide.projects.api.AndroidModule.getCompileSourceDirectories(Unknown Source:12)
	at com.itsaky.androidide.projects.api.ModuleProject.indexSources(Unknown Source:19)
	at com.itsaky.androidide.projects.ProjectManagerImpl$setupProject$4$jobs$1$1.invokeSuspend(Unknown Source:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
```

**Comment by joytou** [comment]
The ide log:

```
~/.androidide $ cat logs/AndroidIDE-LOG-2024-09-01_17:24:34.092.txt
--------- beginning of main
09-01 17:21:56.932 17017 17017 E saky.androidid: LoadAppImageStartupCache enabled : 1
09-01 17:21:56.934 17017 17017 E saky.androidid: Not starting debugger since process cannot load the jdwp agent.
09-01 17:21:57.230 17017 17017 E HwViewGroupImpl: parse speed value length error
09-01 17:21:58.429 17017 17227 E ToolingApiErrorStream:  SLF4J: No SLF4J providers were found.
09-01 17:21:58.429 17017 17227 E ToolingApiErrorStream:  SLF4J: Defaulting to no-operation (NOP) logger implementation
09-01 17:21:58.429 17017 17227 E ToolingApiErrorStream:  SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
09-01 17:22:04.316 17017 17419 E libc    : Access denied finding property "ro.kirin.product.platform"
09-01 17:22:04.354 17017 17426 E ion     : ioctl c0044901 failed with code -1: Not a typewriter
09-01 17:22:10.476 17017 17017 E GradleBuildService:  Failed to shutdown Tooling API server
09-01 17:22:10.476 17017 17017 E GradleBuildService: java.util.concurrent.TimeoutException
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1813)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1943)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at com.itsaky.androidide.services.builder.GradleBuildService.onDestroy(Unknown Source:70)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at android.app.ActivityThread.handleStopService(ActivityThread.java:4993)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at android.app.ActivityThread.access$3400(ActivityThread.java:259)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2502)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at android.os.Handler.dispatchMessage(Handler.java:110)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at android.os.Looper.loop(Looper.java:219)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at android.app.ActivityThread.main(ActivityThread.java:8679)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at java.lang.reflect.Method.invoke(Native Method)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
09-01 17:22:10.476 17017 17017 E GradleBuildService:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
09-01 17:22:10.476 17017 17017 E GradleBuildService:
09-01 17:22:49.279 17017 18302 E ToolingApiErrorStream:  SLF4J: No SLF4J providers were found.
09-01 17:22:49.280 17017 18302 E ToolingApiErrorStream:  SLF4J: Defaulting to no-operation (NOP) logger implementation
09-01 17:22:49.280 17017 18302 E ToolingApiErrorStream:  SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
09-01 17:24:31.575 17017 17089 E BufferQueueProducer: [unnamed-17017-0]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.575 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.581 17017 17089 E BufferQueueProducer: [unnamed-17017-1]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.582 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.585 17017 17089 E BufferQueueProducer: [unnamed-17017-2]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.585 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.588 17017 17089 E BufferQueueProducer: [unnamed-17017-3]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.588 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.590 17017 17089 E BufferQueueProducer: [unnamed-17017-4]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.590 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.593 17017 17089 E BufferQueueProducer: [unnamed-17017-5]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.593 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.595 17017 17089 E BufferQueueProducer: [unnamed-17017-6]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.595 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.598 17017 17089 E BufferQueueProducer: [unnamed-17017-7]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.598 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.600 17017 17089 E BufferQueueProducer: [unnamed-17017-8]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.601 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.603 17017 17089 E BufferQueueProducer: [unnamed-17017-9]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.603 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.606 17017 17089 E BufferQueueProducer: [unnamed-17017-10]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.606 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:31.609 17017 17089 E BufferQueueProducer: [unnamed-17017-11]:163: setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
09-01 17:24:31.609 17017 17089 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
09-01 17:24:33.037 17017 19292 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1609776)
09-01 17:24:33.038 17017 19292 E IDEApplication:  Unable to show crash handler activity
09-01 17:24:33.038 17017 19292 E IDEApplication: android.os.TransactionTooLargeException: data parcel size 1609776 bytes
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.os.BinderProxy.transactNative(Native Method)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.os.BinderProxy.transact(BinderProxy.java:535)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3904)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
09-01 17:24:33.038 17017 19292 E IDEApplication:  Caused by: java.lang.RuntimeException: Failure from system
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1748)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at com.itsaky.androidide.app.IDEApplication$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:179)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
09-01 17:24:33.038 17017 19292 E IDEApplication:        at j
```
