### ISSUE TITLE
I can't initialize project.

### ISSUE THREAD

**Issue by Redoceans** [AndroidIDEOfficial/AndroidIDE#1922]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I download the correct version on github,when I try to Create a new project,AIDE can't initialize project successful .try a lot times,all failed.

### Expected behavior

I hope to Create my first project and initialzed it.

### Version name

[v2.7.1-beta](https://github.com/AndroidIDEOfficial/AndroidIDE/releases/tag/v2.7.1-beta)

### Download source

GitHub

### Relevant log output

```bash
GradleBuildService        I   Showing notification to user... 
EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
EditorActivity            D   No variant selection information available. Default build variants will be selected. 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
ToolingApiServer          D   ToolingApiMain             Running on Java version:  17-internal  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectParams(directory=/storage/emulated/0/AndroidIDEProjects/myfirst, gradleDistribution=GradleDistributionParams(type=GRADLE_WRAPPER, value=), androidParams=AndroidInitializationParams(variantSelections={}))  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 52ms  
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: true 
ToolingApiServer          D   StopWatch                  Project connection established in 15ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, -Pandroidide.logsender.isEnabled=true]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          E   ToolingApiServerImpl       Failed to initialize project 
ToolingApiServer          E  java.net.SocketTimeoutException: Read timed out
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
ToolingApiServer          E  	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1503)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1474)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1059)
ToolingApiServer          E  	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
ToolingApiServer          E  	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
ToolingApiServer          E  	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:141)
ToolingApiServer          E  	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
ToolingApiServer          E  	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3663)
ToolingApiServer          E  	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3656)
ToolingApiServer          E  	at org.gradle.wrapper.Download.downloadInternal(Download.java:135)
ToolingApiServer          E   Caused by: java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-8.1.1-bin.zip failed: timeout (10000ms)
ToolingApiServer          E  	at org.gradle.wrapper.Download.downloadInternal(Download.java:151)
ToolingApiServer          E  	at org.gradle.wrapper.Download.download(Download.java:109)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DistributionInstaller$AsyncDownload$1.run(DistributionInstaller.java:182)
ToolingApiServer          E   Caused by: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-8.1.1-bin.zip'.
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:135)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:41)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:44)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:160)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:142)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:67)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.sync.RootModelBuilder.build(RootModelBuilder.kt:121)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl$initialize$$inlined$runBuild$1.get(ToolingApiServerImpl.kt:483)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
ToolingApiServer          E  
ToolingApiServer          E   
EditorActivity            E   An error occurred initializing the project with Tooling API  null 
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
EditorActivity            D   onBuildStatusChanged: isInitializing: false, isBuildInProgress: false 
EditorActivity            D   [onPause]  No opened files.  Opened files cache reset to null.
```

**Comment by Redoceans** [comment]
~ $ java --version
openjdk 17-internal 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.root.src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc.root.src, mixed mode)
