### ISSUE TITLE
app crash 

### ISSUE THREAD

**Issue by Abanoubeg** [AndroidIDEOfficial/AndroidIDE#1923]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A536E

Stacktrace:
java.lang.IllegalStateException: Circular dependencies cannot exist in RelativeLayout
	at android.widget.RelativeLayout$DependencyGraph.getSortedViews(RelativeLayout.java:1956)
	at android.widget.RelativeLayout.sortChildren(RelativeLayout.java:401)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:409)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(Unknown Source:500)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(Unknown Source:238)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Unknown Source:30)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Unknown Source:99)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Unknown Source:181)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(Unknown Source:436)
	at androidx.core.view.MenuHostHelper.solveLinearSystem(Unknown Source:35)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(Unknown Source:1305)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:1447)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(Unknown Source:6)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(Unknown Source:92)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:396)
	at android.view.View.measure(View.java:28571)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(Unknown Source:245)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1036)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5203)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3973)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

    

### Expected behavior

Application crashes while viewing layout xml

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A536E

### Download source

GitHub

### Relevant log output

```bash
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A536E

Stacktrace:
java.lang.IllegalStateException: Circular dependencies cannot exist in RelativeLayout
	at android.widget.RelativeLayout$DependencyGraph.getSortedViews(RelativeLayout.java:1956)
	at android.widget.RelativeLayout.sortChildren(RelativeLayout.java:401)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:409)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(Unknown Source:500)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(Unknown Source:238)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Unknown Source:30)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Unknown Source:99)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Unknown Source:181)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(Unknown Source:436)
	at androidx.core.view.MenuHostHelper.solveLinearSystem(Unknown Source:35)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(Unknown Source:1305)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:1447)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(Unknown Source:6)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(Unknown Source:92)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:396)
	at android.view.View.measure(View.java:28571)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(Unknown Source:245)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1036)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5203)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3973)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by Abanoubeg** [comment]
Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A536E
