### ISSUE TITLE
It seems like AndroidIDE doesn't supports SplitScreen

### ISSUE THREAD

**Issue by KanhaKanhaiya** [AndroidIDEOfficial/AndroidIDE#213]
**Describe the bug**
After opening AndroidIDE, when I start Split Screen mode the following error occurs and AndroidIDE says to report it :

`AndroidIDE crash report`
```
Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.itsaky.androidide.views.editor.CodeEditorView.getFile()' on a null object reference
	at com.itsaky.androidide.EditorActivity.getEditorForFile(EditorActivity.java:420)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda42.apply(Unknown Source:4)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:203)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:517)
	at com.itsaky.androidide.EditorActivity.closeAll(EditorActivity.java:699)
	at com.itsaky.androidide.EditorActivity.closeProject(EditorActivity.java:1622)
	at com.itsaky.androidide.EditorActivity.onDestroy(EditorActivity.java:1276)
	at android.app.Activity.performDestroy(Activity.java:8180)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1341)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5058)
 Caused by: java.lang.RuntimeException: Unable to destroy activity {com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.itsaky.androidide.views.editor.CodeEditorView.getFile()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5073)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5102)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5387)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5319)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

**To Reproduce**
Open AndroidIDE and press the shortcut key for SplitScreen Mode.

**Expected behavior**
AndroidIDE doesn't crash.

**Details (please complete the following information):**
 - Device: Xiaomi
 - OS: Android 10
 - AndroidIDE Version: Latest from GitHub Actions.

**Additional context**
N/A

**Comment by itsaky** [comment]
Split screens are not supported, yes.

But, this issue should not happen. It'll soon be fixed.

**Comment by KanhaKanhaiya** [comment]
Ok :+1:
