### ISSUE TITLE
[BUG]: ServiceRegisteredException on registering BuildService to Lookup

### ISSUE THREAD

**Issue by SkwizyyyYT** [AndroidIDEOfficial/AndroidIDE#465]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: MI8Lite
App version: 2.1.2-beta_main-b8ab494 (212)

 Stacktrace: 
com.itsaky.androidide.lookup.ServiceRegisteredException
	at com.itsaky.androidide.lookup.internal.DefaultLookup.registerOrUpdate(DefaultLookup.java:98)
	at com.itsaky.androidide.lookup.internal.DefaultLookup.register(DefaultLookup.java:68)
	at com.itsaky.androidide.EditorActivity$1.onServiceConnected(EditorActivity.java:197)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1956)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1988)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by itsaky** [comment]
Any specific way to reproduce this?
