### ISSUE TITLE
[Bug]: Crash on overriding superclass methods

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#492]
### What happened?

IDE Crashed

### What's the expected behavior?

Idk

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-F127G
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-3885d24 (212)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: Column 16 out of bounds. line: 87 , column count (line separator included):6
	at io.github.rosemoe.sora.text.Content.checkLineAndColumn(Content.java:973)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:340)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:333)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction.performEdits(OverrideSuperclassMethodsAction.kt:272)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction.overrideMethods$lambda-10$lambda-9(OverrideSuperclassMethodsAction.kt:248)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction.$r8$lambda$-OfSIOmXuOFUX2KAiKJCL0PZcOo(Unknown Source:0)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction$$ExternalSyntheticLambda1.run(Unknown Source:14)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
How do I reproduce this issue?

**Comment by itsvks19** [comment]
> How do I reproduce this issue?

This issue happens occasionally so how do I reproduce?

**Comment by itsvks19** [comment]
@itsaky Now you should close this issue because for how many days I have not faced it.
