### ISSUE TITLE
[Bug]: Unable to analyze file

### ISSUE THREAD

**Issue by Saint-Theana** [AndroidIDEOfficial/AndroidIDE#507]
### What happened?

Java Lang Server not working,

### What's the expected behavior?

?

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
JavaDiagnosticProvider    W   Unable to analyze file 
JavaDiagnosticProvider    W  java.lang.NullPointerException: type must not be null
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.visitThrow(DiagnosticVisitor.kt:27)
JavaDiagnosticProvider    W  	at com.sun.tools.javac.tree.JCTree$JCThrow.accept(JCTree.java:2)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.scan(DiagnosticVisitor.kt:16)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:3)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:5)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.visitBlock(DiagnosticVisitor.kt:209)
JavaDiagnosticProvider    W  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:2)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.scan(DiagnosticVisitor.kt:16)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:1)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:13)
JavaDiagnosticProvider    W  	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:2)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.scan(DiagnosticVisitor.kt:16)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:3)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:5)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.visitBlock(DiagnosticVisitor.kt:209)
JavaDiagnosticProvider    W  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:2)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.scan(DiagnosticVisitor.kt:16)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:1)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:53)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.visitMethod(DiagnosticVisitor.kt:84)
JavaDiagnosticProvider    W  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:2)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.scan(DiagnosticVisitor.kt:16)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:1)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:3)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:2)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:45)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.visitClass(DiagnosticVisitor.kt:14)
JavaDiagnosticProvider    W  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:2)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.scan(DiagnosticVisitor.kt:16)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:3)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:2)
JavaDiagnosticProvider    W  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:21)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.visitors.DiagnosticVisitor.visitCompilationUnit(DiagnosticVisitor.kt:13)
JavaDiagnosticProvider    W  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:2)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.providers.JavaDiagnosticProvider$AnalyzingThread$run$1.invoke(JavaDiagnosticProvider.kt:377)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.compiler.SynchronizedTask.get(SynchronizedTask.java:8)
JavaDiagnosticProvider    W  	at com.itsaky.androidide.lsp.java.providers.JavaDiagnosticProvider$AnalyzingThread.run(JavaDiagnosticProvider.kt:22)
JavaDiagnosticProvider    W  
JavaDiagnosticProvider    W
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saint-Theana** [comment]
Never mind,maybe caused by low gradle version,after upgraded to gradle 7,it works just fine.

**Comment by Saint-Theana** [comment]
:）
