### ISSUE TITLE
[Bug]: IDE Crashed while adding 'throws' from action menu

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#534]
### What happened?

IDE CRASHED

### What's the expected behavior?

IDE Crashed while adding 'throws' from action menu

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-F127G
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-05790f1 (212)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: Column 66 out of bounds. line: 16 , column count (line separator included):61
	at io.github.rosemoe.sora.text.Content.checkLineAndColumn(Content.java:973)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:340)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:333)
	at com.itsaky.androidide.lsp.IDELanguageClientImpl.lambda$editInEditor$2(IDELanguageClientImpl.java:279)
	at com.itsaky.androidide.lsp.IDELanguageClientImpl$$ExternalSyntheticLambda3.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment]
Fixed!

**Comment by itsvks19** [comment]
Fixed!
