### ISSUE TITLE
[Bug]:  Editor crashes on scroll

### ISSUE THREAD

**Issue by masfha** [AndroidIDEOfficial/AndroidIDE#537]
### What happened?

AndroidIDE Crashed

### What's the expected behavior?

Crash when I change the variable array

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2461
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-b183049 (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=119
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:292)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2382)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1300)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:578)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:177)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3978)
	at android.view.View.draw(View.java:22809)
	at android.view.View.updateDisplayListIfDirty(View.java:21663)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:620)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4763)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4467)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3549)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2322)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9155)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:375)
	at android.view.Choreographer.doFrame(Choreographer.java:913)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by masfha** [comment]
![Screenshot_2022-10-18-08-21-42-63_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/79098759/196313136-b44f7035-3b50-4bc4-8ac0-277252a76796.jpg)

**Comment by itsvks19** [comment]
```
AndroidIDE crash report
Manufacturer: samsung
Device: SM-F127G
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-5d55932 (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:291)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2419)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1328)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:592)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:191)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4029)
	at android.view.View.draw(View.java:23898)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5440)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5148)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by itsvks19** [comment]
It is crashing even in commit (https://github.com/AndroidIDEOfficial/AndroidIDE/commit/5d559322b1ed7e0e8103eaa3e1d9945db57374ff).

**Comment by Trasd** [comment]
AndroidIDE crash report
Manufacturer: LENOVO
Device: LenovoTB-J706F
ABI: arm64-v8a
SDK version: 30
App version: 2.1.2-beta_main-857b10c (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:291)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2419)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1328)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:592)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:191)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4029)
	at android.view.View.draw(View.java:22380)
	at android.view.View.updateDisplayListIfDirty(View.java:21252)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21212)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4133)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3860)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3131)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1974)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8263)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
