### ISSUE TITLE
[Bug]: Crash on clearing logs

### ISSUE THREAD

**Issue by PranavPurwar** [AndroidIDEOfficial/AndroidIDE#540]
### What happened?

The IDE crashes when I try to clear logs during gradle build

### What's the expected behavior?

Should clear the build logs without errors. It might be a bug in sora-editor idk

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote5Pro
ABI: arm64-v8a
SDK version: 28
App version: 2.1.2-beta_main-38dadd2 (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: index = 0, length = 0
	at io.github.rosemoe.sora.util.BlockIntList.set(BlockIntList.java:201)
	at io.github.rosemoe.sora.widget.layout.LineBreakLayout.afterInsert(LineBreakLayout.java:143)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(CodeEditor.java:4270)
	at io.github.rosemoe.sora.text.Content.dispatchAfterInsert(Content.java:936)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:393)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:333)
	at com.itsaky.androidide.views.editor.IDEEditor.append(IDEEditor.java:436)
	at com.itsaky.androidide.fragments.SimpleOutputFragment.lambda$appendOutput$0$com-itsaky-androidide-fragments-SimpleOutputFragment(SimpleOutputFragment.java:56)
	at com.itsaky.androidide.fragments.SimpleOutputFragment$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.fragments.SimpleOutputFragment.appendOutput(SimpleOutputFragment.java:53)
	at com.itsaky.androidide.EditorActivity.appendBuildOut(EditorActivity.java:875)
	at com.itsaky.androidide.handlers.EditorEventListener.onOutput(EditorEventListener.kt:88)
	at com.itsaky.androidide.services.GradleBuildService$1.lambda$onOutput$3(GradleBuildService.java:443)
	at com.itsaky.androidide.services.GradleBuildService$1$$ExternalSyntheticLambda3.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
What additional Gradle commands have you enabled?

**Comment by PranavPurwar** [comment]
It was syncing the project with gradle, I didn't run any other command

**Comment by deepkrg17** [comment]
He was asking which additional gradle commands you have enabled in the Preferences?
Preferences > Build and Run > Additional Gradle commands

**Comment by PranavPurwar** [comment]
only "--info" is checked there

**Comment by itsaky** [comment]
Fixed.
