### ISSUE TITLE
[Bug] Package installer issue on MIUI

### ISSUE THREAD

**Issue by chengzhuangjie** [AndroidIDEOfficial/AndroidIDE#553]
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2012K11AC
ABI: arm64-v8a
SDK version: 30
App version: 2.1.2-beta_main-ba9c7c9 (212)

 Stacktrace: 
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.CONFIRM_INSTALL flg=0x10000000 pkg=com.miui.packageinstaller (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2081)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
	at android.app.Activity.startActivityForResult(Activity.java:5429)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5379)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:5781)
	at android.app.Activity.startActivity(Activity.java:5734)
	at com.itsaky.androidide.utils.InstallationResultHandler.onResult(InstallationResultHandler.kt:76)
	at com.itsaky.androidide.EditorActivity.onNewIntent(EditorActivity.java:973)
	at android.app.Activity.performNewIntent(Activity.java:8163)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1410)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1423)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3762)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3774)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by Otang45** [comment]
+1

**Comment by chengzhuangjie** [comment]
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2012K11AC
ABI: arm64-v8a
SDK version: 30
App version: 2.1.2-beta_main-b16dc13 (212)

 Stacktrace: 
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.CONFIRM_INSTALL flg=0x10000000 pkg=com.miui.packageinstaller (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2081)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
	at android.app.Activity.startActivityForResult(Activity.java:5429)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5379)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:5781)
	at android.app.Activity.startActivity(Activity.java:5734)
	at com.itsaky.androidide.utils.InstallationResultHandler.onResult(InstallationResultHandler.kt:76)
	at com.itsaky.androidide.EditorActivity.onNewIntent(EditorActivity.java:981)
	at android.app.Activity.performNewIntent(Activity.java:8163)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1410)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1423)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3762)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3774)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
