### ISSUE TITLE
[Bug]: App is crashing adding sourceSets to build.gradle.

### ISSUE THREAD

**Issue by Lyanna234** [AndroidIDEOfficial/AndroidIDE#566]
### What happened?

This is my build.gradle file bro. I am trying to add sourceSets to have subfolders in res layout folder. App is crashing when rebuilding again. After the IDE Logs is generating ResourceTableEntry.

### What's the expected behavior?

Hope the app will not crash when editing the build.gradle file

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

AndroidIDE crash report
Manufacturer: TECNO MOBILE LIMITED
Device: TECNOCH6n
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-ba9c7c9 (212)
Stacktrace: 
java.lang.IllegalArgumentException: No enum constant com.android.aaptcompiler.AaptResourceType.FRAGMENTS
	at java.lang.Enum.valueOf(Enum.java:259)
	at com.android.aaptcompiler.AaptResourceType.valueOf(Unknown Source:2)
	at com.itsaky.androidide.xml.resources.internal.DefaultResourceTableRegistry.addFileReferences(DefaultResourceTableRegistry.kt:233)
	at com.itsaky.androidide.xml.resources.internal.DefaultResourceTableRegistry.forPackage(DefaultResourceTableRegistry.kt:88)
	at com.itsaky.androidide.projects.api.AndroidModule.getResourceTable(AndroidModule.kt:305)
	at com.itsaky.androidide.projects.api.AndroidModule.readResources$lambda$3(AndroidModule.kt:255)
	at com.itsaky.androidide.projects.api.AndroidModule.$r8$lambda$ezEjVC_fEanOEVCGs8CY2ky3U7A(Unknown Source:0)
	at com.itsaky.androidide.projects.api.AndroidModule$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
What's the error? It is most probably an issue with your project and not the IDE. I would recommend you check out the documentation for the same.

**Comment by Lyanna234** [comment]
![Screenshot_20221030-205428](https://user-images.githubusercontent.com/116910101/198879735-bca8c778-6412-4740-b32a-0bce11da9c95.jpg)
Bro Itsaky I could not provide you the Stacktrace coz the app is stopping.

**Comment by Lyanna234** [comment]
The app will crash if sourceSets has a wrong directory. Just have to be careful on it. I made it successfully 🥰 Thanks AndroidIDE

**Comment by itsaky** [comment]
The `sourceSets` issue is with your project and not the IDE. Please read the Android Developer documentation.

However, the crash issue has been fixed.
