### ISSUE TITLE
[Bug]: App crashing when typing

### ISSUE THREAD

**Issue by friostd** [AndroidIDEOfficial/AndroidIDE#569]
### What happened?

The IDE is crashing out of nowhere when typing.

### What's the expected behavior?

That it doesn't crash when typing.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A315G
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-8bbdaff (212)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: invalid bounds
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:442)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:410)
	at io.github.rosemoe.sora.widget.EditorInputConnection.deleteSurroundingText(EditorInputConnection.java:360)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:732)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lyanna234** [comment]
This is older beta. Update your app coz this is a duplicate issue.

**Comment by FrioGitHub** [comment]
@Lyanna234 I'm on the latest version.
