### ISSUE TITLE
[Bug]: When commenting some java codes in code editor

### ISSUE THREAD

**Issue by smith8h** [AndroidIDEOfficial/AndroidIDE#582]
### What happened?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote6Pro
ABI: arm64-v8a
SDK version: 28
App version: 2.1.2-beta_main-a76eec2 (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=108
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:292)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2382)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1300)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:578)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:177)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3978)
	at android.view.View.draw(View.java:20234)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3418)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3195)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2564)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7421)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
	at android.view.Choreographer.doFrame(Choreographer.java:819)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

### What's the expected behavior?

need to be fixed

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment]
This is fixed. Use latest build.

**Comment by smith8h** [comment]
thanks
