### ISSUE TITLE
[Bug]: The app is crashing when I am using regex.

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#588]
### What happened?

The app is crashing when I am using regex.

### What's the expected behavior?

🥲

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-F127G
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-5d55932 (212)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'int io.github.rosemoe.sora.util.LongArrayList.size()' on a null object reference
	at io.github.rosemoe.sora.widget.EditorSearcher.gotoNext(EditorSearcher.java:121)
	at io.github.rosemoe.sora.widget.IDEEditorSearcher.gotoNext(IDEEditorSearcher.kt:84)
	at com.itsaky.androidide.views.editor.EditorSearchLayout.onSearchActionClick(EditorSearchLayout.kt:125)
	at com.itsaky.androidide.views.editor.EditorSearchLayout.$r8$lambda$22w8P0EJTDkXDPGAdJ9jVD1HwKA(Unknown Source:0)
	at com.itsaky.androidide.views.editor.EditorSearchLayout$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7792)
	at android.widget.TextView.performClick(TextView.java:16112)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1219)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in https://github.com/Rosemoe/sora-editor/commit/b238031d8661155bffeb7d8be33da7ea0c9b2135.
