### ISSUE TITLE
[Bug]: StringIndexOutOfBoundsException in EditorInputConnection

### ISSUE THREAD

**Issue by pdt012** [AndroidIDEOfficial/AndroidIDE#613]
### What happened?

When I select a variable name and use backspace to delete the word(then type the new name), the ide crashed when I pressed backspace.
Actually the app crash whenever I type on a selected word.

### What's the expected behavior?

It didn't happen on v2.1.1.
Please fix it as soon as possible.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G977N
ABI: arm64-v8a
SDK version: 31
App version: 2.1.3-beta (213)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:133)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:96)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:561)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in https://github.com/Rosemoe/sora-editor/commit/34fe871470e13bea90bd0d0ad98b8f8564983a5e.
