### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by ibnuwahyudi86** [AndroidIDEOfficial/AndroidIDE#622]
AndroidIDE crash report
Manufacturer: Sony
Device: SOV39
ABI: arm64-v8a
SDK version: 29
App version: 2.1.3-beta (213)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:34)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:111)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:101)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:10)
	at android.view.View.draw(View.java:21455)
	at android.view.View.updateDisplayListIfDirty(View.java:20332)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw(View.java:21458)
	at android.view.View.updateDisplayListIfDirty(View.java:20332)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw(View.java:21458)
	at android.view.View.updateDisplayListIfDirty(View.java:20332)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:14)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:104)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.updateDisplayListIfDirty(View.java:20323)
	at android.view.View.draw(View.java:21187)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw(View.java:21458)
	at com.android.internal.policy.DecorView.draw(DecorView.java:822)
	at android.view.View.updateDisplayListIfDirty(View.java:20332)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3616)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3424)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2761)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1727)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7612)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
	at android.view.Choreographer.doCallbacks(Choreographer.java:852)
	at android.view.Choreographer.doFrame(Choreographer.java:787)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7418)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by itsaky** [comment]
Duplicate of #537.
