### ISSUE TITLE
[Bug]: IDE Installation complete auto-focus

### ISSUE THREAD

**Issue by ThatMG393** [AndroidIDEOfficial/AndroidIDE#628]
### What happened?

See the video for more information...
https://user-images.githubusercontent.com/73651803/203890621-c7d5ab4d-65f2-42a0-a966-8aa6b3d71ca6.mp4

It launches a new activity then the new service binds to the current service then when opening a file it crashes...

### What's the expected behavior?

It should go back to the same activity

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```
 --------- beginning of crash

11-25 10:44:12.314 23033 23033 E AndroidRuntime: FATAL EXCEPTION: main

11-25 10:44:12.314 23033 23033 E AndroidRuntime: Process: com.itsaky.androidide, PID: 23033

11-25 10:44:12.314 23033 23033 E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter server

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.itsaky.androidide.language.CommonCompletionProvider.<init>(Unknown Source:2)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.itsaky.androidide.language.java.JavaLanguage.<init>(JavaLanguage.java:55)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.itsaky.androidide.views.editor.CodeEditorView.createLanguage(CodeEditorView.java:203)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.itsaky.androidide.views.editor.CodeEditorView.postRead(CodeEditorView.java:166)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.itsaky.androidide.views.editor.CodeEditorView.lambda$new$0$com-itsaky-androidide-views-editor-CodeEditorView(CodeEditorView.java:131)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.itsaky.androidide.views.editor.CodeEditorView$$ExternalSyntheticLambda0.run(Unknown Source:6)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6942)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)

11-25 10:44:12.314 23033 23033 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> See the video for more information...
https://user-images.githubusercontent.com/73651803/203890621-c7d5ab4d-65f2-42a0-a966-8aa6b3d71ca6.mp4

The file is corrupt. Please upload it again.

**Comment by ThatMG393** [comment]
@itsaky I don't know how to fix it, every video file I upload is corrupt...
