### ISSUE TITLE
[Bug]: crashed when long click item and move it in layout editor (layout designer)

### ISSUE THREAD

**Issue by smith8h** [AndroidIDEOfficial/AndroidIDE#647]
### What happened?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote6Pro
ABI: arm64-v8a
SDK version: 28
App version: 2.1.3-beta_main-b6afb51 (213)

 Stacktrace: 
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5038)
	at android.view.ViewGroup.addView(ViewGroup.java:4869)
	at android.view.ViewGroup.addView(ViewGroup.java:4809)
	at com.itsaky.androidide.inflater.internal.ViewGroupImpl.addChild(ViewGroupImpl.kt:48)
	at com.itsaky.androidide.uidesigner.drag.WidgetDragListener.onDrag(WidgetDragListener.kt:55)
	at android.view.View.callDragEventHandler(View.java:24277)
	at android.view.ViewRootImpl.setDragFocus(ViewRootImpl.java:6652)
	at android.view.View.dispatchDragEvent(View.java:24266)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1776)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6531)
	at android.view.ViewRootImpl.access$1000(ViewRootImpl.java:139)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4398)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

### What's the expected behavior?

fix the issue when possible

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in recent commits.
