### ISSUE TITLE
[Bug]: app close on swipe by my java code

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#654]
### What happened?

I was looking for an error in my java code, while scrolling up, the app crashed

### What's the expected behavior?

Slide through my code, see the error and fix it.

### What version of AndroidIDE you're using?

v2.1.3

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G973U1
ABI: arm64-v8a
SDK version: 31
App version: 2.1.3-beta (213)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:34)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:111)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:101)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:10)
	at android.view.View.draw(View.java:23898)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5414)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5122)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4186)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2893)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10445)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This is supposed to be fixed in recent commits. Could you check this issue with the debug (GitHub Actions) builds?

**Comment by esalessandrxx** [comment]
Yes, thanks I try with the debug version

**Comment by esalessandrxx** [comment]
Yes, the application is still buggy. Note that my code has parts where it uses deprecated codes.

#### BUG #### 

AndroidIDE crash report
Manufacturer: samsung
Device: SM-G973U1
ABI: arm64-v8a
SDK version: 31
App version: 2.1.3-beta_main-908c79f (213)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:291)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2419)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1328)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:592)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:191)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4029)
	at android.view.View.draw(View.java:23898)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
	at android.view.View.updateDisplayListIfDirty(View.java:22714)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5414)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5122)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4186)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2893)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10445)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
