### ISSUE TITLE
bootstrap installation failed

### ISSUE THREAD

**Issue by DereckySany** [AndroidIDEOfficial/AndroidIDE#659]
### What happened?

- apparently it is not possible to create all the directories and files in the app directory, necessary for its use.

### What's the expected behavior?

the app should be able to copy and create files in its app directory.

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report

ABI: arm64-v8a
SDK version: 29
App version: 2.1.3-beta (213)

 Stacktrace: 
com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:478)
 Caused by: java.util.concurrent.CompletionException: com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:481)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Duplicate of #601.
