### ISSUE TITLE
[Bug]: Failed Initialize Project

### ISSUE THREAD

**Issue by ghodel-dev** [AndroidIDEOfficial/AndroidIDE#724]
### What happened?

![Screenshot_20230106-064643_AndroidIDE](https://user-images.githubusercontent.com/66862348/210901356-404f837b-fd5d-4202-877f-292361cc8d0f.png)

File :
[ide_logs.txt](https://github.com/AndroidIDEOfficial/AndroidIDE/files/10356344/ide_logs.txt)

### What's the expected behavior?

successfully initialized the project

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Relevant log output

```shell
GradleBuildService        I   Showing notification to user... 
GradleBuildService        D   onBind() called with: intent = [Intent { cmp=com.itsaky.androidide/.services.GradleBuildService }] 
EditorActivity            I   Connected to Gradle build service 
GradleBuildService        I   Starting tooling API server... 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectMessage(directory=/storage/emulated/0/AndroidIDEProjects/Example, gradleInstallation=)  
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 327ms  
ToolingApiServer          D   StopWatch                  Project connection established in 175ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --stacktrace]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          E   ToolingApiServerImpl      
ToolingApiServer          E  org.gradle.launcher.daemon.client.NoUsableDaemonFoundException: A new daemon was started but could not be connected to: pid=DaemonInfo{pid=16182, address=[3ddb47ea-b5fa-4765-9fbf-89933ec4cd08 port:39813, addresses:[/127.0.0.1]], state=Busy, lastBusy=1672962156218, context=DefaultDaemonContext[uid=64178a76-e0da-4dec-b388-54306218071d,javaHome=/data/data/com.itsaky.androidide/files/usr/opt/openjdk,daemonRegistryDir=/data/data/com.itsaky.androidide/files/home/.gradle/daemon,pid=16182,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country,-Duser.language=en,-Duser.variant]}, address= [3ddb47ea-b5fa-4765-9fbf-89933ec4cd08 port:39813, addresses:[/127.0.0.1]]. See https://docs.gradle.org/7.4.2/userguide/troubleshooting.html#network_connection for more details.
ToolingApiServer          E  	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:172)
ToolingApiServer          E  	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:44)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:30)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:222)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.ProviderConnection.runClientAction(ProviderConnection.java:168)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:158)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:234)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ParameterizedActionRunner.execute(ParameterizedActionRunner.java:36)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableActionRunner.run(CancellableActionRunner.java:52)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:69)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:56)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:81)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E   Caused by: org.gradle.tooling.GradleConnectionException: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:67)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.util.ProjectReader.read(ProjectReader.java:107)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl.initialize$lambda$0(ToolingApiServerImpl.kt:109)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
ToolingApiServer          E  
ToolingApiServer          E   
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
DefaultActionsRegistry    I   Action 'Run tasks' completed in 18ms 
EditorActivity            D   Is project initialized: true 
EditorActivity            D   Sending init request to tooling server.. 
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectMessage(directory=/storage/emulated/0/AndroidIDEProjects/Example, gradleInstallation=)  
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 2ms  
ToolingApiServer          D   StopWatch                  Project connection established in 24ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --stacktrace]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          E   ToolingApiServerImpl      
ToolingApiServer          E  org.gradle.launcher.daemon.client.NoUsableDaemonFoundException: A new daemon was started but could not be connected to: pid=DaemonInfo{pid=16871, address=[488ece2d-8ce1-44a0-bf09-40c99bd9e2f0 port:38633, addresses:[/127.0.0.1]], state=Busy, lastBusy=1672962234473, context=DefaultDaemonContext[uid=6499af23-777e-422d-bada-256de0637b2b,javaHome=/data/data/com.itsaky.androidide/files/usr/opt/openjdk,daemonRegistryDir=/data/data/com.itsaky.androidide/files/home/.gradle/daemon,pid=16871,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country,-Duser.language=en,-Duser.variant]}, address= [488ece2d-8ce1-44a0-bf09-40c99bd9e2f0 port:38633, addresses:[/127.0.0.1]]. See https://docs.gradle.org/7.4.2/userguide/troubleshooting.html#network_connection for more details.
ToolingApiServer          E  	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:172)
ToolingApiServer          E  	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:44)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:30)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:222)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.ProviderConnection.runClientAction(ProviderConnection.java:168)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:158)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:234)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ParameterizedActionRunner.execute(ParameterizedActionRunner.java:36)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableActionRunner.run(CancellableActionRunner.java:52)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:69)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:56)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:81)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E   Caused by: org.gradle.tooling.GradleConnectionException: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:67)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.util.ProjectReader.read(ProjectReader.java:107)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl.initialize$lambda$0(ToolingApiServerImpl.kt:109)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
ToolingApiServer          E  
ToolingApiServer          E   
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers...
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The VPN service you're using might cause this issue. Please disconnect from the VPN and try again.

**Comment by ghodel-dev** [comment]
> The VPN service you're using might cause this issue. Please disconnect from the VPN and try again.
> 
> From Gradle docs :
> 
> > The solution to this problem is to adjust your network configuration such that local connections are not modified to appear as from external addresses.

**Comment by ghodel-dev** [comment]
I'm trying witout

**Comment by ghodel-dev** [comment]
I'm trying without VPN network but still error, how many data packets are needed to initialize the project ?

[build_output.txt](https://github.com/AndroidIDEOfficial/AndroidIDE/files/10357712/build_output.txt)

**Comment by ghodel-dev** [comment]
> The VPN service you're using might cause this issue. Please disconnect from the VPN and try again.
> 
> From Gradle docs :
> 
> > The solution to this problem is to adjust your network configuration such that local connections are not modified to appear as from external addresses.
