### ISSUE TITLE
[Bug]:  Unexpected closing of the app in version 2.1.4-beta (214)

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#725]
### What happened?

When changing from dark theme to light theme the app was closed..

Ps. Please update the Android IDE version on Github when opening a report, it only shows version 2.1.3 debug builds

### What's the expected behavior?

Change the subject without suffering a shutdown

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G973U1
ABI: arm64-v8a
SDK version: 31
App version: 2.1.4-beta (214)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage(int, java.lang.Object)' on a null object reference
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager.insert(AsyncIncrementalAnalyzeManager.java:44)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(CodeEditor.java:219)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:303)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:10)
	at com.itsaky.androidide.editor.ui.IDEEditor.append(IDEEditor.java:27)
	at com.itsaky.androidide.fragments.LogViewFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:54)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:11)
	at com.itsaky.androidide.fragments.LogViewFragment.appendLog(LogViewFragment.kt:111)
	at com.itsaky.androidide.fragments.IDELogFragment$$ExternalSyntheticLambda0.log(R8$$SyntheticClass:66)
	at com.itsaky.androidide.utils.ILogger.log(ILogger.java:292)
	at com.itsaky.androidide.utils.ILogger.error(ILogger.java:3)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onStart(EditorHandlerActivity.kt:125)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8315)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Seems to be an issue with the editor itself. I'll look into it.

**Comment by itsaky** [comment]
> Ps. Please update the Android IDE version on Github when opening a report, it only shows version 2.1.3 debug builds.

Thanks for pointing this out.

**Comment by MrIkso** [comment]
It maybe fixed on next sora editor version
