### ISSUE TITLE
Please fix bug

### ISSUE THREAD

**Issue by LIHOV8** [AndroidIDEOfficial/AndroidIDE#744]
### What happened?

AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2043
ABI: arm64-v8a
SDK version: 31
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.IllegalArgumentException: Value must be a reference to a drawable resource type. '@raw/'
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.throwInvalidResType(basicParseUtils.kt:17)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(AbstractParser.kt:11)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(AbstractParser.kt:15)
	at com.itsaky.androidide.inflater.internal.adapters.ImageViewAdapter$createAttrHandlers$8.invoke(ImageViewAdapter.kt:21)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(IViewAdapter.kt:20)
	at com.itsaky.androidide.inflater.IViewAdapter$apply$1.invoke(IViewAdapter.kt:10)
	at com.itsaky.androidide.inflater.IViewAdapter.doApply(IViewAdapter.kt:62)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(IViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(ViewImpl.kt:40)
	at com.itsaky.androidide.uidesigner.fragments.AttrValueEditorFragment$showAttrInfo$1$2.invoke(AttrValueEditorFragment.kt:65)
	at com.sun.tools.javac.main.JavaCompiler$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:35)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2043
ABI: arm64-v8a
SDK version: 31
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.IllegalArgumentException: Value must be a reference to a drawable resource type. '@raw/'
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.throwInvalidResType(basicParseUtils.kt:17)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(AbstractParser.kt:11)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(AbstractParser.kt:15)
	at com.itsaky.androidide.inflater.internal.adapters.ImageViewAdapter$createAttrHandlers$8.invoke(ImageViewAdapter.kt:21)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(IViewAdapter.kt:20)
	at com.itsaky.androidide.inflater.IViewAdapter$apply$1.invoke(IViewAdapter.kt:10)
	at com.itsaky.androidide.inflater.IViewAdapter.doApply(IViewAdapter.kt:62)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(IViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(ViewImpl.kt:40)
	at com.itsaky.androidide.uidesigner.fragments.AttrValueEditorFragment$showAttrInfo$1$2.invoke(AttrValueEditorFragment.kt:65)
	at com.sun.tools.javac.main.JavaCompiler$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:35)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2043
ABI: arm64-v8a
SDK version: 31
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.IllegalArgumentException: Value must be a reference to a drawable resource type. '@raw/'
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.throwInvalidResType(basicParseUtils.kt:17)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(AbstractParser.kt:11)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(AbstractParser.kt:15)
	at com.itsaky.androidide.inflater.internal.adapters.ImageViewAdapter$createAttrHandlers$8.invoke(ImageViewAdapter.kt:21)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(IViewAdapter.kt:20)
	at com.itsaky.androidide.inflater.IViewAdapter$apply$1.invoke(IViewAdapter.kt:10)
	at com.itsaky.androidide.inflater.IViewAdapter.doApply(IViewAdapter.kt:62)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(IViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(ViewImpl.kt:40)
	at com.itsaky.androidide.uidesigner.fragments.AttrValueEditorFragment$showAttrInfo$1$2.invoke(AttrValueEditorFragment.kt:65)
	at com.sun.tools.javac.main.JavaCompiler$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:35)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
It's no bug

**Comment by itsaky** [comment]
> Value must be a reference to a drawable resource type. '@raw/'

You are providing a reference to a raw resource as the attribute value, but reference to a drawable resource was expected. That's why the exception.

However, the IDE will not crash for such issues after the commit I added. It will instead log warning messages in IDE logs.
