### ISSUE TITLE
[Bug]:in Android 13 when i click open the app after installation it crashed

### ISSUE THREAD

**Issue by ALEX5402** [AndroidIDEOfficial/AndroidIDE#759]
### What happened?

Crash in Android 13

### What's the expected behavior?

When i try to click open the app it crashed

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: realme
Device: realmeMonet
ABI: arm64-v8a
SDK version: 33
App version: v2.2.0-beta (220)

 Stacktrace: 
android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1110)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1032)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:721)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1302)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1243)

	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1110)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1032)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:721)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1302)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1243)
 Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.alex cmp=com.alex/.HelloJni } from ProcessRecord{9d65895 6850:com.itsaky.androidide/u0a171} (pid=6850, uid=10171) not exported from uid 10197
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2054)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1837)
	at android.app.Activity.startActivityForResult(Activity.java:5471)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5429)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:5927)
	at android.app.Activity.startActivity(Activity.java:5894)
	at com.itsaky.androidide.fragments.CrashReportFragment$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:77)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:8)
	at android.view.View.performClick(View.java:7506)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:10)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29341)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please check if your application's launcher activity is exported or not.

Learn more about [`<activity>.exported`](https://developer.android.com/guide/topics/manifest/activity-element#exported).
Learn more about the [`android:exported` behavior change in Android 12](https://developer.android.com/about/versions/12/behavior-changes-12#exported).

**Comment by ALEX5402** [comment]
Yes sir its fixed now my app ishu in code i was opened my old project and
set my main activity export to false accidentally  so thats why it's happen
i realise that after some times
