### ISSUE TITLE
Crashed when i clicked on onClick(View) in button onclicklistener

### ISSUE THREAD

**Issue by JUDE122-MAX** [AndroidIDEOfficial/AndroidIDE#764]
### What happened?

I was trying to use the new View.OnClickListener with a FAB when i clicked on the onClick(View) it crashed showing the error provided 

### What's the expected behavior?

It was supposed to add an override method of onClick

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: HMD Global
Device: Nokia1.4
ABI: armeabi-v7a
SDK version: 30
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: Column 16 out of bounds. line: 26 , column count (line separator included):6
	at io.github.rosemoe.sora.text.Content.checkLineAndColumn(Content.java:45)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:9)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:10)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:103)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
It's fixed on https://github.com/AndroidIDEOfficial/AndroidIDE/commit/b9bef990428f70e3c8147fa450f2a8bb67282675
