### ISSUE TITLE
AndroidIDE Crashed saying IndexOutOfBound while selecting texts from the editor

### ISSUE THREAD

**Issue by Petersburg2020** [AndroidIDEOfficial/AndroidIDE#771]
### What happened?

IDE suddenly crashed while I was trying to select some texts, and it threw an exception saying IndexOutOfBound.

### What's the expected behavior?

It is supposed to select texts and allow me to copy, paste it delete texts depending on my choice for that moment

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2239
ABI: arm64-v8a
SDK version: 29
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:34)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:111)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:879)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:10)
	at android.view.View.draw(View.java:21822)
	at android.view.View.updateDisplayListIfDirty(View.java:20644)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:20595)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4150)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3938)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3240)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2075)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8471)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
	at android.view.Choreographer.doCallbacks(Choreographer.java:889)
	at android.view.Choreographer.doFrame(Choreographer.java:816)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1050)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7824)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
It's fixed on https://github.com/AndroidIDEOfficial/AndroidIDE/commit/b9bef990428f70e3c8147fa450f2a8bb67282675
