### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MohammedKHC** [AndroidIDEOfficial/AndroidIDE#772]
### What happened?

Crash

### What's the expected behavior?

Crash

### What version of AndroidIDE you're using?

v2.2.0

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2010J19SG
ABI: arm64-v8a
SDK version: 31
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:34)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:111)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:879)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:10)
	at android.view.View.draw(View.java:23031)
	at android.view.View.updateDisplayListIfDirty(View.java:21899)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21850)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4655)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4373)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3484)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2275)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9002)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1182)
	at android.view.Choreographer.doCallbacks(Choreographer.java:972)
	at android.view.Choreographer.doFrame(Choreographer.java:895)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1164)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8322)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
Duplicate of #771.
