### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by JUDE122-MAX** [AndroidIDEOfficial/AndroidIDE#778]
### What happened?

I was using the app then suddenly it crashed 

### What's the expected behavior?

Just crashed

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: HMD Global
Device: Nokia1.4
ABI: armeabi-v7a
SDK version: 30
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage(int, java.lang.Object)' on a null object reference
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager.insert(AsyncIncrementalAnalyzeManager.java:44)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(CodeEditor.java:219)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:303)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:10)
	at com.itsaky.androidide.editor.ui.IDEEditor.append(IDEEditor.java:27)
	at com.itsaky.androidide.fragments.LogViewFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:23)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:11)
	at com.itsaky.androidide.fragments.LogViewFragment.appendLog(LogViewFragment.kt:111)
	at com.itsaky.androidide.fragments.IDELogFragment$$ExternalSyntheticLambda0.log(R8$$SyntheticClass:66)
	at com.itsaky.androidide.utils.ILogger.log(ILogger.java:292)
	at com.itsaky.androidide.utils.ILogger.error(ILogger.java:3)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onStart(EditorHandlerActivity.kt:125)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3458)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
It's maybe fixed on https://github.com/AndroidIDEOfficial/AndroidIDE/commit/b9bef990428f70e3c8147fa450f2a8bb67282675
Update your version
