### ISSUE TITLE
[Bug]: No Activity found to handle Intent action OPEN_DOCUMENT_TREE

### ISSUE THREAD

**Issue by BrotherBoard** [AndroidIDEOfficial/AndroidIDE#833]
### What happened?

Android 13 ARM64 user here!
used language: kotlin
spent 6min building and it ended up doing success building.
now trying to build app and it crashed. I've got logs.

### What's the expected behavior?

Should basically proceed the app building process?

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)
latest as from Wed, Mar 1 2023

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A105F
ABI: arm64-v8a
SDK version: 33
App version: v2.3.0-beta (230)

 Stacktrace: 
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2206)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1845)
	at android.app.Activity.startActivityForResult(Activity.java:5489)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:1)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:157)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:26)
	at androidx.fragment.app.Fragment$10.launch(Fragment.java:11)
	at com.itsaky.androidide.fragments.MainFragment$onViewCreated$openProject$1.invoke(MainFragment.kt:31)
	at com.itsaky.androidide.adapters.MainActionsListAdapter$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:36)
	at android.view.View.performClick(View.java:7506)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:10)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29356)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

### Duplicate issues

- [x] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Hey there @BrotherBoard,

This looks like an issue specific to your device. Could you check if the Files app (`com.android.documentsui`) on your device is installed and enabled?

Also, I would like to know the name and version of the OS you're using.

**Comment by itsaky** [comment]
The IDE should not crash after 66b7f570db9ad9cebecc369491e2713a2ce04457.
