### ISSUE TITLE
[Bug]: Crashed on startup on Lenovo Tablet

### ISSUE THREAD

**Issue by Third-Jaruda** [AndroidIDEOfficial/AndroidIDE#838]
### What happened?

App crashed upon opening after sucessful install

### What's the expected behavior?

App shouldn't crash on first startup.

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: LENOVO
Device: LenovoTB-X606X
ABI: arm64-v8a
SDK version: 29
App version: v2.3.0-beta (230)

 Stacktrace: 
org.greenrobot.eventbus.EventBusException: Default instance already exists. It may be only set once before it's used the first time to ensure consistent behavior.
	at com.itsaky.androidide.app.IDEApplication.onCreate(IDEApplication.kt:145)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6501)
 Caused by: java.lang.RuntimeException: Unable to create application com.itsaky.androidide.app.IDEApplication: org.greenrobot.eventbus.EventBusException: Default instance already exists. It may be only set once before it's used the first time to ensure consistent behavior.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6506)
	at android.app.ActivityThread.access$1400(ActivityThread.java:227)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1888)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
Duplicate #809
