### ISSUE TITLE
[Bug]: AndroidIDE slow and causing crash

### ISSUE THREAD

**Issue by ghost** [AndroidIDEOfficial/AndroidIDE#839]
### What happened?

After compiling the app I exited it, when I came back it got slow and showed the error.

### What's the expected behavior?

Return to the app without any problem

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G975W
ABI: arm64-v8a
SDK version: 31
App version: v2.3.0-beta.internal.1+branch.dev.commit.920c29a.timestamp.20230305034510 (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleServiceBinder.getService(GradleServiceBinder.kt:35)
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:37)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2235)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2268)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Check if [this](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/4336446435) build fixes the crash or not.
