### ISSUE TITLE
[Bug]: 崩溃

### ISSUE THREAD

**Issue by BrotherShuiling** [AndroidIDEOfficial/AndroidIDE#841]
### What happened?

AndroidIDE crash report
Manufacturer: vivo
Device: V1901A
ABI: arm64-v8a
SDK version: 28
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.OutOfMemoryError: Failed to allocate a 159902488 byte allocation with 2080768 free bytes and 148MB until OOM, max allowed footprint 383622656, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3260)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.ensureCapacity(AbstractStringBuilder.java:112)
	at java.lang.StringBuilder.ensureCapacity(StringBuilder.java:77)
	at io.github.rosemoe.sora.text.Content.toStringBuilder(Content.java:13)
	at io.github.rosemoe.sora.text.Content.toString(Content.java:1)
	at com.itsaky.androidide.editor.ui.IDEEditor.setFile(IDEEditor.java:26)
	at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:370)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: vivo
Device: V1901A
ABI: arm64-v8a
SDK version: 28
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.OutOfMemoryError: Failed to allocate a 159902488 byte allocation with 2080768 free bytes and 148MB until OOM, max allowed footprint 383622656, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3260)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.ensureCapacity(AbstractStringBuilder.java:112)
	at java.lang.StringBuilder.ensureCapacity(StringBuilder.java:77)
	at io.github.rosemoe.sora.text.Content.toStringBuilder(Content.java:13)
	at io.github.rosemoe.sora.text.Content.toString(Content.java:1)
	at com.itsaky.androidide.editor.ui.IDEEditor.setFile(IDEEditor.java:26)
	at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:370)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: vivo
Device: V1901A
ABI: arm64-v8a
SDK version: 28
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.OutOfMemoryError: Failed to allocate a 159902488 byte allocation with 2080768 free bytes and 148MB until OOM, max allowed footprint 383622656, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3260)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.ensureCapacity(AbstractStringBuilder.java:112)
	at java.lang.StringBuilder.ensureCapacity(StringBuilder.java:77)
	at io.github.rosemoe.sora.text.Content.toStringBuilder(Content.java:13)
	at io.github.rosemoe.sora.text.Content.toString(Content.java:1)
	at com.itsaky.androidide.editor.ui.IDEEditor.setFile(IDEEditor.java:26)
	at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:370)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
What file were you trying to open?

**Comment by itsaky** [comment]
The file is just too big to open in the editor (`159MB`). However, in order to avoid the crash, a file size limit has been added which restricts opening files above 10MB (f3f577ab951c9651b38efe65c85978fd64d9ede6).
