### ISSUE TITLE
Android ide Crash 

### ISSUE THREAD

**Issue by mohammad-ayan-008** [AndroidIDEOfficial/AndroidIDE#842]
### What's the expected behavior?

-> Ide Crash

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```
AndroidIDE crash report
Manufacturer: INFINIX MOBILITY LIMITED
Device: InfinixX680D
ABI: armeabi-v7a
SDK version: 29
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:34)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:111)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:113)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:34)
	at android.view.View.draw(View.java:21571)
	at android.view.View.updateDisplayListIfDirty(View.java:20414)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4457)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4430)
	at android.view.View.updateDisplayListIfDirty(View.java:20365)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3781)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3585)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2905)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1818)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7913)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:980)
	at android.view.Choreographer.doCallbacks(Choreographer.java:804)
	at android.view.Choreographer.doFrame(Choreographer.java:739)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7593)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
Fixed https://github.com/AndroidIDEOfficial/AndroidIDE/commit/58b7662635eb71599374543e9efdd57aad7b016b
