### ISSUE TITLE
[Bug]: Crash while modifying the AndroidIDE UI

### ISSUE THREAD

**Issue by vip458** [AndroidIDEOfficial/AndroidIDE#852]
### What happened?

A crash occurred while modifying the UI

### What's the expected behavior?

Hope to refine it in the next release to make AndroidIDE more stable

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2012K11AC
ABI: arm64-v8a
SDK version: 33
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2232)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2265)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
Duplicate #839
