### ISSUE TITLE
[Bug]: App Crashes when changing theme

### ISSUE THREAD

**Issue by SnowAkira09876** [AndroidIDEOfficial/AndroidIDE#854]
### What happened?

When you are on editor, the app crashes after changing app theme.

### What's the expected behavior?

No crashes.

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: TECNO MOBILE LIMITED
Device: TECNOCH6n
ABI: arm64-v8a
SDK version: 31
App version: v2.3.0-beta.internal.1+branch.dev.commit.d81c553.timestamp.20230309175236 (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleServiceBinder.getService(GradleServiceBinder.kt:35)
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:37)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2095)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2128)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:342)
	at android.app.ActivityThread.main(ActivityThread.java:8118)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
Duplicate #839
