### ISSUE TITLE
When I open the AndroidIDE app, it shows an error.

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [AndroidIDEOfficial/AndroidIDE#858]
AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi8
ABI: arm64-v8a
SDK version: 29
App version: v2.3.0-beta (230)

 Stacktrace: 
```org.greenrobot.eventbus.EventBusException: Default instance already exists. It may be only set once before it's used the first time to ensure consistent behavior.
	at com.itsaky.androidide.app.IDEApplication.onCreate(IDEApplication.kt:145)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
 Caused by: java.lang.RuntimeException: Unable to create application com.itsaky.androidide.app.IDEApplication: org.greenrobot.eventbus.EventBusException: Default instance already exists. It may be only set once before it's used the first time to ensure consistent behavior.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6587)
	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by MrIkso** [comment]
Duplicate #809
