### ISSUE TITLE
[Bug]: There was a bug when editing the xml layout, when I was editing the width and height.

### ISSUE THREAD

**Issue by rubensfox20** [AndroidIDEOfficial/AndroidIDE#867]
### What happened?

There was a bug when editing the xml layout, when I was editing the width and height.

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: samsung
Device: SM-A025M
ABI: armeabi-v7a
SDK version: 31
App version: 2.1.3-beta (213)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:133)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:96)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:561)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### What version of AndroidIDE you're using?

v2.1.3

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This issue has already been fixed. Update AndroidIDE to the latest version.
