### ISSUE TITLE
[Bug]: error when app was minimized

### ISSUE THREAD

**Issue by rubensfox20** [AndroidIDEOfficial/AndroidIDE#870]
### What happened?

I left the app minimized, when I went back to it it gave this error.

### What's the expected behavior?

I hoped it didn't give an error when I went back to the app again

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A025M
ABI: armeabi-v7a
SDK version: 31
App version: v2.4.0-beta (240)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2240)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2273)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Should have been fixed with ded4409. Please reopen this issue if it isn't.
