### ISSUE TITLE
[{Bug}]: no indents

### ISSUE THREAD

**Issue by AlloMoondragon** [AndroidIDEOfficial/AndroidIDE#872]
### What happened?

I think all these are related.
My AndroidIde crashes often upon opening files with the attached error ~which mentions indents.
And no matter which settings I turn on or off, there is no indent detection at all for me ~on any project.  Every line starts at the far left wall.
I have to manually push space a bunch or copypaste a bunch of spaces.  But a single backspace deletrs them all and returns to the above line.

https://user-images.githubusercontent.com/127817827/225852889-cded3ce7-5ed2-4788-b18d-7bff66c51cf7.mp4

### What's the expected behavior?

im using 2.4 even tho the spinner below this trxt box only goes up to 2.3.  also first time github idk exactly what this textbox is asking :)

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A136U
ABI: armeabi-v7a
SDK version: 31
App version: v2.4.0-beta (240)

 Stacktrace: 
java.lang.IllegalArgumentException: query(name:indents) parsing failed: Capture at text offset 1151787008
 at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguageSpec.<init>(TreeSitterLanguageSpec.kt:60)
 at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:179)
 at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.<init>(KotlinLanguage.kt:12)
 at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage$$ExternalSyntheticLambda0.create(R8$$SyntheticClass:3)
 at com.itsaky.androidide.editor.ui.IDEEditor.setupLanguage(IDEEditor.java:53)
 at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:169)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8751)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlloMoondragon** [comment]
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A136U
ABI: armeabi-v7a
SDK version: 31
App version: v2.4.0-beta (240)

 Stacktrace: 
java.lang.IllegalArgumentException: query(name:indents) parsing failed: Capture at text offset 1151787008
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguageSpec.<init>(TreeSitterLanguageSpec.kt:60)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:179)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.<init>(KotlinLanguage.kt:12)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage$$ExternalSyntheticLambda0.create(R8$$SyntheticClass:3)
	at com.itsaky.androidide.editor.ui.IDEEditor.setupLanguage(IDEEditor.java:53)
	at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:169)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

still very often upon opening file
