### ISSUE TITLE
[Bug]: This bug occurred when reopening the app

### ISSUE THREAD

**Issue by rubensfox20** [AndroidIDEOfficial/AndroidIDE#910]
### What happened?

This bug occurred when reopening the app

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: samsung
Device: SM-A025M
ABI: armeabi-v7a
SDK version: 31
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2240)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2273)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Duplicate of #870.
