### ISSUE TITLE
[Bug]: Chased on implementing abstract methods

### ISSUE THREAD

**Issue by MrIkso** [AndroidIDEOfficial/AndroidIDE#916]
### What happened?

Chased on implementing abstract methods

### What's the expected behavior?

No crash

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-M526B
ABI: arm64-v8a
SDK version: 33
App version: v2.4.1-beta.internal.1+branch.dev.commit.402c3f6.timestamp.20230331184636 (241)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: Column 48 out of bounds. line: 76 , column count (line separator included):10
	at io.github.rosemoe.sora.text.Content.checkLineAndColumn(Content.java:1059)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:357)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:350)
	at com.itsaky.androidide.lsp.IDELanguageClientImpl.lambda$editInEditor$2(IDELanguageClientImpl.java:268)
	at com.itsaky.androidide.lsp.IDELanguageClientImpl$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you provide more information about the issue? Maybe a sample file?
