### ISSUE TITLE
[Bug]: Crash when opening AndroidIDE from recent applications

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#951]
### What happened?

AndroidIDE crashed when opening it from recent applications.

From here:

![Screenshot_2023-04-18-12-24-45-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/102840735/232695798-1356d833-0451-484a-829f-3e8f634ee5a1.jpg)

### What's the expected behavior?

Shouldn't crash.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2495
ABI: arm64-v8a
SDK version: 33
App version: v2.4.1-beta.internal.1+branch.dev.commit.8446212.timestamp.20230414031403 (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleServiceBinder.getService(GradleServiceBinder.kt:35)
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:37)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2320)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2353)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8373)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatMG393** [comment]
Duplicate of issue #870

**Comment by itsvks19** [comment]
> Duplicate of issue #870

Sorry
