### ISSUE TITLE
[Bug]: Sora editor

### ISSUE THREAD

**Issue by jonstudio8** [AndroidIDEOfficial/AndroidIDE#962]
### What happened?

When writing codes, Sora Editor crashes.

### What's the expected behavior?

No error when writing code.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A127M
ABI: arm64-v8a
SDK version: 33
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at io.github.rosemoe.sora.widget.CodeEditor.findCursorBlock(CodeEditor.java:49)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelection(CodeEditor.java:9)
	at io.github.rosemoe.sora.widget.CodeEditor.setSelection(CodeEditor.java:1)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:320)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:95)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl.lambda$commitText$16$com-android-internal-inputmethod-RemoteInputConnectionImpl(RemoteInputConnectionImpl.java:569)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda34.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please report this in [sora-editor](https://github.com/Rosemoe/sora-editor).
