### ISSUE TITLE
[Bug]: Crash on overriding abstract methods

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [AndroidIDEOfficial/AndroidIDE#978]
### What happened?

I clicked on override super class method and app crashed.

### What's the expected behavior?

App crashed and throws a error.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2006C3MII
ABI: armeabi-v7a
SDK version: 29
App version: v2.4.0-beta.internal.1+branch.b4ba1a19b261271a285bb68b7afdbad3537b3916.commit.b4ba1a1.timestamp.20230318100039 (240)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: Column 8 out of bounds. line: 143 , column count (line separator included):3
	at io.github.rosemoe.sora.text.Content.checkLineAndColumn(Content.java:1059)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:357)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:350)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction.performEdits(OverrideSuperclassMethodsAction.kt:269)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction.overrideMethods$lambda$9$lambda$8(OverrideSuperclassMethodsAction.kt:245)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction.$r8$lambda$3SBpXZo4OAK8npuQhBd0kEyBesM(Unknown Source:0)
	at com.itsaky.androidide.lsp.java.actions.generators.OverrideSuperclassMethodsAction$$ExternalSyntheticLambda1.run(Unknown Source:14)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
It's a same #916

**Comment by itsaky** [comment]
@MrIkso Thanks.
